// src/balancing/config/idleVillage/defaultConfig.ts
// Minimal default IdleVillageConfig. Intentionally almost empty so that
// all domain content is authored via config/UI rather than hardcoded here.

import type { IdleVillageConfig } from './types';
import type { StatBlock } from '@/balancing/types';
import { DEFAULT_PASSIVE_EFFECTS } from './passiveEffects';

type NumericStatKey = Exclude<keyof StatBlock, 'configFlatFirst' | 'configApplyBeforeCrit'>;

const ZEROED_STAT_SNAPSHOT: StatBlock = {
  hp: 0,
  damage: 0,
  txc: 0,
  evasion: 0,
  agility: 0,
  hitChance: 0,
  effectiveDamage: 0,
  attacksPerKo: 0,
  htk: 0,
  edpt: 0,
  ttk: 0,
  earlyImpact: 0,
  critChance: 0,
  critMult: 0,
  critTxCBonus: 0,
  failChance: 0,
  failMult: 0,
  failTxCMalus: 0,
  armor: 0,
  resistance: 0,
  armorPen: 0,
  penPercent: 0,
  lifesteal: 0,
  regen: 0,
  ward: 0,
  block: 0,
  energyShield: 0,
  thorns: 0,
  cooldownReduction: 0,
  castSpeed: 0,
  movementSpeed: 0,
  configFlatFirst: false,
  configApplyBeforeCrit: false,
};

const createSnapshot = (boostedStats: NumericStatKey[]): Partial<StatBlock> => {
  const snapshot: Partial<StatBlock> = { ...ZEROED_STAT_SNAPSHOT };
  boostedStats.forEach((stat) => {
    snapshot[stat] = 25;
  });
  return snapshot;
};

export const DEFAULT_IDLE_VILLAGE_CONFIG: IdleVillageConfig = {
  version: '1.0.0',

  // Core economic resources for the village meta-game. All values are editable
  // from the Idle Village config UI; these are just safe starting presets for
  // the first playable scenario.
  resources: {
    gold: {
      id: 'gold',
      label: 'Gold',
      description: 'Coins used for wages, equipment and basic upgrades.',
      icon: '◆',
      colorClass: 'text-amber-300',
      isCore: true,
    },
    food: {
      id: 'food',
      label: 'Food',
      description: 'Daily upkeep for all residents in the village.',
      icon: '♨',
      colorClass: 'text-emerald-300',
      isCore: true,
    },
    materials: {
      id: 'materials',
      label: 'Materials',
      description: 'Abstract building materials for construction and upgrades.',
      icon: '⬤',
      colorClass: 'text-slate-200',
      isCore: true,
    },
    xp: {
      id: 'xp',
      label: 'XP',
      description: 'Experience gained from combat and risky jobs.',
      icon: '✦',
      colorClass: 'text-violet-300',
      isCore: true,
    },
    ember_sigils: {
      id: 'ember_sigils',
      label: 'Ember Sigils',
      description: 'Seared currency granted to residents who survive Trial of Fire assignments.',
      icon: '🔥',
      colorClass: 'text-amber-300',
    },
    radiant_ore: {
      id: 'radiant_ore',
      label: 'Radiant Ore',
      description: 'Luminous ore harvested from stabilized storm nodes.',
      icon: '💎',
      colorClass: 'text-sky-300',
    },
    ashen_favor: {
      id: 'ashen_favor',
      label: 'Ashen Favor',
      description: 'Political weight issued by the Silent Order for perfect upkeep.',
      icon: '🕯️',
      colorClass: 'text-rose-200',
    },
    chronicle_shards: {
      id: 'chronicle_shards',
      label: 'Chronicle Shards',
      description: 'Encoded battle reports, used to unlock high-tier tactics.',
      icon: '📜',
      colorClass: 'text-emerald-200',
    },
  },

  // Minimal starting activities: core jobs + an early quest to exercise
  // the time, job, quest and injury engines.
  activities: {
    job_city_rats: {
      id: 'job_city_rats',
      label: 'Clear Rats in City',
      description: 'Hunt rats in the city sewers for a small but steady income.',
      tags: ['job', 'combat', 'city'],
      slotTags: ['village', 'job_site'],
      resolutionEngineId: 'job',
      level: 1,
      dangerRating: 1,
      durationFormula: '1',
      maxSlots: 'infinite',
      statRequirement: {
        label: 'Discipline + (Edge | Lantern)',
        allOf: ['discipline'],
        anyOf: ['edge', 'lantern'],
      },
      // Simple deterministic rewards; fully configurable from the Activities tab.
      rewards: [
        { resourceId: 'gold', amountFormula: '5' },
        { resourceId: 'xp', amountFormula: '2' },
      ],
      metadata: {
        // Allow this job to auto-repeat in the main Idle Village UI.
        supportsAutoRepeat: true,
        // Default map slot; still overridable via Activities/Map config.
        mapSlotId: 'village_square',
        // Mark this as a continuous job: while assigned, it pays out once per time segment.
        continuousJob: true,
      },
    },
    job_explore_outskirts: {
      id: 'job_explore_outskirts',
      label: 'Explore the Outskirts',
      description: 'Scout the outskirts for threats and opportunities.',
      tags: ['job', 'explore'],
      slotTags: ['world', 'job_site'],
      resolutionEngineId: 'job',
      level: 1,
      dangerRating: 2,
      durationFormula: '5',
      maxSlots: 'infinite',
      statRequirement: {
        label: 'Lantern Tracker',
        allOf: ['lantern'],
        noneOf: ['frailty'],
      },
      rewards: [
        { resourceId: 'xp', amountFormula: '3' },
        { resourceId: 'materials', amountFormula: '1' },
      ],
      metadata: {
        supportsAutoRepeat: false,
        mapSlotId: 'village_gate',
      },
    },
    job_training_basics: {
      id: 'job_training_basics',
      label: 'Basic Training',
      description: 'Light drills and exercises to improve fundamentals.',
      tags: ['job', 'training'],
      slotTags: ['village', 'job_site'],
      resolutionEngineId: 'job',
      level: 1,
      dangerRating: 0,
      durationFormula: '2',
      maxSlots: 'infinite',
      statRequirement: {
        label: 'Reason Focus',
        allOf: ['reason'],
      },
      rewards: [
        { resourceId: 'xp', amountFormula: '4' },
      ],
      metadata: {
        supportsAutoRepeat: true,
        mapSlotId: 'village_square',
        trainingProgramId: 'basic_combat',
      },
    },
    quest_city_rats: {
      id: 'quest_city_rats',
      label: 'Cull Rats in Sewers',
      description: 'A riskier extermination quest in the city sewers: better XP, but chance of injury.',
      tags: ['quest', 'combat', 'city'],
      slotTags: ['city', 'job_site'],
      resolutionEngineId: 'quest_combat',
      level: 1,
      dangerRating: 2,
      durationFormula: '3',
      maxSlots: 'infinite',
      statRequirement: {
        label: 'Edge Veteran',
        allOf: ['edge'],
        anyOf: ['discipline', 'moth'],
      },
      // Quest rewards are explicit XP resource; QuestResolver also reports xpAwarded.
      rewards: [
        { resourceId: 'xp', amountFormula: '6' },
      ],
      metadata: {
        mapSlotId: 'village_square',
        verbToneId: 'danger',
        // Enable quest spawning for the vertical slice.
        questSpawnEnabled: true,
        questSpawnWeight: 3,
        questMinDay: 1,
        questMaxConcurrent: 2,
        questAllowedSlotTags: ['city'],
        // UI-only display hints for FTUE: not used by engines yet.
        injuryChanceDisplay: 35,
        deathChanceDisplay: 5,
      },
    },
    job_visit_market: {
      id: 'job_visit_market',
      label: 'Visit Market',
      description: 'Spend some time at the market to open trading opportunities.',
      tags: ['job', 'market'],
      slotTags: ['village', 'job_site', 'shop'],
      resolutionEngineId: 'job',
      level: 1,
      dangerRating: 0,
      durationFormula: '1',
      maxSlots: 'infinite',
      statRequirement: {
        label: 'Lantern or Reason',
        anyOf: ['lantern', 'reason'],
      },
      // No direct rewards; buying food is handled by the Market UI using
      // baseFoodPriceInGold from globalRules.
      rewards: [],
      metadata: {
        mapSlotId: 'village_market',
        marketJob: true,
      },
    },
    job_custode_sigilli: {
      id: 'job_custode_sigilli',
      label: 'Custode dei Sigilli di Grano',
      description: 'Rafforza i filamenti runici dei silo che alimentano il Trial of Fire.',
      tags: ['job', 'logistics'],
      slotTags: ['village', 'job_site'],
      resolutionEngineId: 'job',
      level: 2,
      dangerRating: 1,
      durationFormula: '3',
      maxSlots: 2,
      slotModifiers: {
        0: { yieldMult: 1 },
        1: { yieldMult: 1.15, fatigueMult: 1.05 },
      },
      statRequirement: {
        label: 'Discipline & Lantern',
        allOf: ['discipline'],
        anyOf: ['lantern'],
      },
      rewards: [
        { resourceId: 'ember_sigils', amountFormula: '3' },
        { resourceId: 'ashen_favor', amountFormula: '1' },
      ],
      metadata: {
        supportsAutoRepeat: true,
        mapSlotId: 'village_square',
        icon: '🌾',
        injuryChanceDisplay: 6,
        deathChanceDisplay: 2,
      },
    },
    job_idromante_cisterne: {
      id: 'job_idromante_cisterne',
      label: 'Idromante delle Cisterne',
      description: 'Mantieni il flusso delle cisterne cristalline con canti idromantici.',
      tags: ['job', 'support'],
      slotTags: ['village', 'job_site'],
      resolutionEngineId: 'job',
      level: 2,
      dangerRating: 1,
      durationFormula: '2',
      statRequirement: {
        label: 'Lantern Cantor',
        allOf: ['lantern'],
        noneOf: ['frailty'],
      },
      rewards: [
        { resourceId: 'ember_sigils', amountFormula: '2' },
        { resourceId: 'chronicle_shards', amountFormula: '1' },
      ],
      metadata: {
        supportsAutoRepeat: true,
        mapSlotId: 'village_square',
        icon: '💧',
        maxCrewSize: 1,
        injuryChanceDisplay: 4,
        deathChanceDisplay: 1,
      },
    },
    job_cartografo_lucciole: {
      id: 'job_cartografo_lucciole',
      label: 'Cartografo delle Lucciole',
      description: 'Segui le lucciole eteree e aggiorna le mappe dei corridoi sicuri.',
      tags: ['job', 'scouting'],
      slotTags: ['village', 'job_site'],
      resolutionEngineId: 'job',
      level: 2,
      dangerRating: 1,
      durationFormula: '4',
      statRequirement: {
        label: 'Lantern Tracker',
        allOf: ['lantern'],
        anyOf: ['moth'],
      },
      rewards: [
        { resourceId: 'ember_sigils', amountFormula: '2' },
        { resourceId: 'radiant_ore', amountFormula: '1' },
      ],
      metadata: {
        supportsAutoRepeat: false,
        mapSlotId: 'village_gate',
        icon: '🕯',
        maxCrewSize: 1,
        injuryChanceDisplay: 5,
        deathChanceDisplay: 2,
      },
    },
    job_sentinella_vetro_aurico: {
      id: 'job_sentinella_vetro_aurico',
      label: 'Sentinella del Vetro Aurico',
      description: 'Pattuglia il bastione di vetro aurico e rinforza gli scudi notturni.',
      tags: ['job', 'defense'],
      slotTags: ['village', 'job_site'],
      resolutionEngineId: 'job',
      level: 3,
      dangerRating: 2,
      durationFormula: '3',
      statRequirement: {
        label: 'Edge Bastion',
        allOf: ['edge', 'discipline'],
      },
      rewards: [
        { resourceId: 'ember_sigils', amountFormula: '3' },
        { resourceId: 'ashen_favor', amountFormula: '1' },
      ],
      metadata: {
        supportsAutoRepeat: true,
        mapSlotId: 'village_square',
        icon: '🛡️',
        maxCrewSize: 2,
        injuryChanceDisplay: 7,
        deathChanceDisplay: 3,
      },
    },
    job_archivista_frammenti: {
      id: 'job_archivista_frammenti',
      label: 'Archivista dei Frammenti',
      description: 'Cataloga frammenti di reliquie e aggiorna i registri del Trial of Fire.',
      tags: ['job', 'scholar'],
      slotTags: ['village', 'job_site'],
      resolutionEngineId: 'job',
      level: 2,
      dangerRating: 1,
      durationFormula: '2',
      statRequirement: {
        label: 'Reason Scholar',
        allOf: ['reason'],
      },
      rewards: [
        { resourceId: 'ember_sigils', amountFormula: '2' },
        { resourceId: 'chronicle_shards', amountFormula: '2' },
      ],
      metadata: {
        supportsAutoRepeat: true,
        mapSlotId: 'village_market',
        icon: '🧩',
        maxCrewSize: 1,
        injuryChanceDisplay: 3,
        deathChanceDisplay: 1,
      },
    },
    quest_fornaci_spettro: {
      id: 'quest_fornaci_spettro',
      label: 'Assalto alle Fornaci Spettro',
      description: 'Spezza le catene delle fornaci infestate dai wraith e riconfigura i crogioli.',
      tags: ['quest', 'combat'],
      slotTags: ['world', 'job_site'],
      resolutionEngineId: 'quest_combat',
      level: 4,
      dangerRating: 6,
      durationFormula: '4',
      statRequirement: {
        label: 'Edge or Forge Savant',
        anyOf: ['edge', 'forge'],
        noneOf: ['frailty'],
      },
      rewards: [
        { resourceId: 'ember_sigils', amountFormula: '6' },
        { resourceId: 'radiant_ore', amountFormula: '2' },
        { resourceId: 'chronicle_shards', amountFormula: '1' },
      ],
      metadata: {
        icon: '🔥',
        verbToneId: 'danger',
        questSpawnEnabled: true,
        questSpawnWeight: 4,
        questMinDay: 2,
        questMaxConcurrent: 2,
        questAllowedSlotTags: ['world'],
        mapSlotId: 'village_gate',
        maxCrewSize: 3,
        injuryChanceDisplay: 58,
        deathChanceDisplay: 38,
      },
    },
    quest_corridor_ceneri: {
      id: 'quest_corridor_ceneri',
      label: 'Duello nel Corridoio delle Ceneri',
      description: 'Affronta il campione del Corridoio per ottenere i suoi pattern rituali.',
      tags: ['quest', 'combat'],
      slotTags: ['world', 'job_site'],
      resolutionEngineId: 'quest_combat',
      level: 5,
      dangerRating: 7,
      durationFormula: '3',
      statRequirement: {
        label: 'Discipline Duelist',
        allOf: ['discipline'],
        anyOf: ['edge', 'heart'],
      },
      rewards: [
        { resourceId: 'ember_sigils', amountFormula: '5' },
        { resourceId: 'ashen_favor', amountFormula: '3' },
        { resourceId: 'chronicle_shards', amountFormula: '2' },
      ],
      metadata: {
        icon: '⚔️',
        verbToneId: 'danger',
        questSpawnEnabled: true,
        questSpawnWeight: 3,
        questMinDay: 3,
        questMaxConcurrent: 1,
        questAllowedSlotTags: ['world'],
        maxCrewSize: 2,
        injuryChanceDisplay: 65,
        deathChanceDisplay: 42,
      },
    },
    quest_nodo_tempesta: {
      id: 'quest_nodo_tempesta',
      label: 'Incursione al Nodo Tempesta',
      description: 'Stabilizza il nodo tempestoso prima che cancelli l’avamposto.',
      tags: ['quest', 'arcane'],
      slotTags: ['world', 'job_site'],
      resolutionEngineId: 'quest_combat',
      level: 6,
      dangerRating: 8,
      durationFormula: '4',
      statRequirement: {
        label: 'Lantern Anchor',
        allOf: ['lantern'],
        anyOf: ['reason'],
      },
      rewards: [
        { resourceId: 'ember_sigils', amountFormula: '7' },
        { resourceId: 'radiant_ore', amountFormula: '3' },
        { resourceId: 'ashen_favor', amountFormula: '2' },
      ],
      metadata: {
        icon: '⚡',
        verbToneId: 'danger',
        questSpawnEnabled: true,
        questSpawnWeight: 3,
        questMinDay: 4,
        questMaxConcurrent: 1,
        questAllowedSlotTags: ['world'],
        maxCrewSize: 3,
        injuryChanceDisplay: 70,
        deathChanceDisplay: 47,
      },
    },
    quest_rituale_sangue_stellare: {
      id: 'quest_rituale_sangue_stellare',
      label: 'Rituale del Sangue Stellare',
      description: 'Canalizza il sangue stellare per chiudere una frattura dimensionale.',
      tags: ['quest', 'ritual'],
      slotTags: ['world', 'job_site'],
      resolutionEngineId: 'quest_combat',
      level: 6,
      dangerRating: 8,
      durationFormula: '5',
      statRequirement: {
        label: 'Moth or Winter Choir',
        anyOf: ['moth', 'winter'],
      },
      rewards: [
        { resourceId: 'ember_sigils', amountFormula: '8' },
        { resourceId: 'ashen_favor', amountFormula: '2' },
        { resourceId: 'chronicle_shards', amountFormula: '2' },
      ],
      metadata: {
        icon: '🩸',
        verbToneId: 'danger',
        questSpawnEnabled: true,
        questSpawnWeight: 2,
        questMinDay: 5,
        questMaxConcurrent: 1,
        questAllowedSlotTags: ['world'],
        maxCrewSize: 3,
        injuryChanceDisplay: 74,
        deathChanceDisplay: 55,
      },
    },
    quest_caccia_tiranno_ossidiano: {
      id: 'quest_caccia_tiranno_ossidiano',
      label: 'Caccia al Tiranno Ossidiano',
      description: 'Abbatti il tiranno ossidiano che domina le steppe vulcaniche.',
      tags: ['quest', 'combat'],
      slotTags: ['world', 'job_site'],
      resolutionEngineId: 'quest_combat',
      level: 7,
      dangerRating: 9,
      durationFormula: '6',
      statRequirement: {
        label: 'Edge & Heart Vanguard',
        allOf: ['edge', 'heart'],
      },
      rewards: [
        { resourceId: 'ember_sigils', amountFormula: '9' },
        { resourceId: 'radiant_ore', amountFormula: '3' },
        { resourceId: 'chronicle_shards', amountFormula: '3' },
      ],
      metadata: {
        icon: '💀',
        verbToneId: 'danger',
        questSpawnEnabled: true,
        questSpawnWeight: 2,
        questMinDay: 6,
        questMaxConcurrent: 1,
        questAllowedSlotTags: ['world'],
        maxCrewSize: 4,
        injuryChanceDisplay: 82,
        deathChanceDisplay: 60,
      },
    },
  },

  // Simple logical map layout with two generic slots: one inside the village
  // and one just outside the walls. Coordinates are purely logical and the UI
  // is responsible for normalising them.
  mapLayout: {
    pixelWidth: 1280,
    pixelHeight: 720,
  },
  mapSlots: {
    village_square: {
      id: 'village_square',
      label: 'Village Square',
      description: 'Central hub for simple city jobs.',
      x: 420,
      y: 460,
      slotTags: ['village', 'job_site', 'city'],
      isInitiallyUnlocked: true,
      icon: '★',
      colorClass: 'text-amber-200',
    },
    village_gate: {
      id: 'village_gate',
      label: 'Village Gate',
      description: 'Edge of the village, entry point to the outskirts.',
      x: 1080,
      y: 260,
      slotTags: ['world', 'job_site'],
      isInitiallyUnlocked: true,
      icon: '⇨',
      colorClass: 'text-sky-200',
    },
    village_market: {
      id: 'village_market',
      label: 'Market',
      description: 'A small trading stall inside the village walls.',
      x: 760,
      y: 380,
      slotTags: ['village', 'job_site', 'shop'],
      isInitiallyUnlocked: true,
      icon: '◎',
      colorClass: 'text-emerald-200',
    },
  },

  // Starting buildings are currently informational; future engines can read
  // their bonuses. They are still fully editable from the Buildings tab.
  passiveEffects: DEFAULT_PASSIVE_EFFECTS,

  buildings: {
    founder_house: {
      id: 'founder_house',
      label: "Founder’s House",
      description: 'Basic housing for the founder and first residents.',
      tags: ['house', 'village'],
      isInitiallyBuilt: true,
    },
    city_sewers: {
      id: 'city_sewers',
      label: 'City Sewers',
      description: 'Access point to the rat-infested sewers beneath the village.',
      tags: ['job_site', 'combat', 'village'],
      isInitiallyBuilt: true,
    },
    village_wall_gate: {
      id: 'village_wall_gate',
      label: 'Village Gate',
      description: 'Where residents leave the safety of the walls to explore.',
      tags: ['job_site', 'world'],
      isInitiallyBuilt: true,
    },
    village_market: {
      id: 'village_market',
      label: 'Village Market',
      description: 'Basic trading post used to buy food and goods.',
      tags: ['shop', 'village'],
      isInitiallyBuilt: true,
      level: 1,
      maxLevel: 3,
      upgrades: [
        {
          level: 2,
          costs: {
            gold: 50,
            materials: 5,
          },
          notes: 'Unlocks better stall space and more efficient trading.',
        },
        {
          level: 3,
          costs: {
            gold: 120,
            materials: 15,
          },
          notes: 'Full market square with multiple stalls and improved prices.',
        },
      ],
    },
  },

  // Founder presets define starting characters per difficulty. Engines will resolve
  // these archetype references and apply the adjustment formulas during run creation.
  founders: {
    founder_sunblade: {
      id: 'founder_sunblade',
      label: 'Sir Ardan Sunblade',
      description: 'Veteran vigil-knight who keeps the ember banners alight.',
      archetypeId: 'trial_vindicator',
      difficultyTag: 'legend',
      statTags: ['edge', 'lantern', 'discipline'],
      statSnapshot: createSnapshot(['hp', 'damage', 'armor']),
      isHero: true,
    },
    founder_penumbral: {
      id: 'founder_penumbral',
      label: 'Lyss Penumbria',
      description: 'Shadow cartomancer who scouts the Trial corridors.',
      archetypeId: 'trial_stalker',
      difficultyTag: 'skirmisher',
      statTags: ['moth', 'edge', 'lantern'],
      statSnapshot: createSnapshot(['txc', 'evasion', 'agility']),
      isHero: false,
    },
    founder_starseer: {
      id: 'founder_starseer',
      label: 'Celeste Asteria',
      description: 'Starborne duelist who bends constellations into blades.',
      archetypeId: 'trial_constellation',
      difficultyTag: 'heroic',
      statTags: ['lantern', 'reason', 'edge'],
      statSnapshot: createSnapshot(['critChance', 'critMult', 'penPercent']),
      isHero: true,
    },
    founder_fluxmender: {
      id: 'founder_fluxmender',
      label: 'Ilyon Fluxmender',
      description: 'Ward-smith tending the shimmering shields atop the walls.',
      archetypeId: 'trial_integrator',
      difficultyTag: 'support',
      statTags: ['heart', 'forge', 'reason'],
      statSnapshot: createSnapshot(['ward', 'regen', 'energyShield']),
      isHero: false,
    },
  },

  // Neutral variance config so that QuestResolver can opt into categories
  // later without forcing any randomness on the first jobs.
  variance: {
    difficultyCategories: {
      normal: {
        id: 'normal',
        label: 'Normal Difficulty',
        minMultiplier: 1,
        maxMultiplier: 1,
        weight: 1,
      },
      safe: {
        id: 'safe',
        label: 'Under-Tuned',
        description: 'Activities resolving a bit easier than expected.',
        colorClass: 'text-emerald-300',
        minMultiplier: 0.8,
        maxMultiplier: 0.95,
        weight: 0.2,
      },
      risky: {
        id: 'risky',
        label: 'Over-Tuned',
        description: 'Tougher encounters with higher injury risk.',
        colorClass: 'text-rose-300',
        minMultiplier: 1.05,
        maxMultiplier: 1.3,
        weight: 0.3,
      },
    },
    rewardCategories: {
      normal: {
        id: 'normal',
        label: 'Normal Reward',
        minMultiplier: 1,
        maxMultiplier: 1,
        weight: 1,
      },
      lean: {
        id: 'lean',
        label: 'Underpaid',
        description: 'Reward variance on the low side.',
        colorClass: 'text-amber-200',
        minMultiplier: 0.7,
        maxMultiplier: 0.9,
        weight: 0.25,
      },
      lavish: {
        id: 'lavish',
        label: 'Heroic Reward',
        description: 'High payout missions with flashy loot.',
        colorClass: 'text-sky-200',
        minMultiplier: 1.15,
        maxMultiplier: 1.4,
        weight: 0.2,
      },
    },
  },

  globalRules: {
    // These numbers are safe placeholders and should be tuned via config/UI.
    maxFatigueBeforeExhausted: 100,
    fatigueRecoveryPerDay: 50,
    dayLengthInTimeUnits: 5,
    secondsPerTimeUnit: 60,
    fatigueYellowThreshold: 33,
    fatigueRedThreshold: 66,
    baseLightInjuryChanceAtMaxFatigue: 0.3,
    dangerInjuryMultiplierPerPoint: 0.1,
    injuryTiers: {
      light: {
        id: 'light',
        label: 'Light Injury',
        description: 'Bruises and sprains; resident still functional.',
        recoveryTimeInDays: 1,
        jobEfficiencyMultiplier: 0.85,
        questEligibility: 'limited',
        fatigueGainMultiplier: 1.1,
        colorClass: 'text-amber-200',
      },
      moderate: {
        id: 'moderate',
        label: 'Moderate Injury',
        description: 'Serious wounds that need proper care.',
        recoveryTimeInDays: 3,
        jobEfficiencyMultiplier: 0.65,
        questEligibility: 'none',
        fatigueGainMultiplier: 1.3,
        colorClass: 'text-orange-300',
      },
      severe: {
        id: 'severe',
        label: 'Severe Injury',
        description: 'Life-threatening state requiring infirmary time.',
        recoveryTimeInDays: 7,
        jobEfficiencyMultiplier: 0.4,
        questEligibility: 'none',
        fatigueGainMultiplier: 1.5,
        colorClass: 'text-rose-300',
      },
    },
    deathRules: {
      baseDeathChanceAtMaxDanger: 0.05,
      dangerDeathMultiplierPerPoint: 0.02,
      injuryTierMultipliers: {
        light: 0.5,
        moderate: 1,
        severe: 1.5,
      },
      questOutcomeAdjustments: {
        perfect: -0.02,
        success: -0.01,
        partial: 0,
        fail: 0.03,
        deadly: 0.1,
      },
      starvationDeathChancePerDay: 0.02,
    },
    foodConsumptionPerResidentPerDay: 1,
    baseFoodPriceInGold: 25,
    startingResources: {
      gold: 0,
      food: 2,
    },
    // Simple base formula, expected to be overridden from the config UI.
    questXpFormula: 'level * 10',
    maxActiveQuests: 5,
    // Minimal quest spawning defaults for the vertical slice.
    // One spawn check per day, up to a small number of offers.
    questSpawnEveryNDays: 1,
    maxGlobalQuestOffers: 4,
    maxQuestOffersPerSlot: 2,
    verbToneColors: {
      neutral: '#94A3B8',
      job: '#3B82F6',
      quest: '#34D399',
      danger: '#F87171',
      system: '#38BDF8',
    },
  },

  overlaySettings: {
    enabled: true,
    defaultPosition: 'top-right',
    defaultSize: 'medium',
    defaultZoom: 1.0,
    alwaysOnTop: true,
    transparency: false,
    enabledWidgets: [
      { id: 'resources', enabled: true, order: 0 },
      { id: 'activities', enabled: true, order: 1 },
      { id: 'time', enabled: true, order: 2 },
      { id: 'villagers', enabled: true, order: 3 },
    ],
    autoHideTimeoutSeconds: 0,
    showSystemTrayIcon: true,
  },
  uiPreferences: {
    defaultAppTabId: 'villageSandbox',
  },
};
