import type { SavedCharacter } from '@/engine/idle/characterTypes';
import type { StatBlock } from '@/balancing/types';
import { DEFAULT_STATS } from '@/balancing/types';

const createStatBlock = (overrides: Partial<StatBlock>): StatBlock => ({
  ...DEFAULT_STATS,
  ...overrides,
});

const DEFAULT_TIMESTAMP = 1769160000000; // 2026-01-24T00:00:00.000Z

export const TEST_ROSTER_HEROES: SavedCharacter[] = [
  {
    id: 'hero-sir-spaccaculi',
    name: 'Sir Spaccaculi',
    aiBehavior: 'tank',
    statBlock: createStatBlock({
      hp: 280,
      damage: 24,
      txc: 22,
      evasion: 6,
      agility: 42,
      armor: 35,
      resistance: 18,
      block: 28,
    }),
    equippedSpellIds: [],
    visualProfileId: 'hero-tank',
    status: 'available',
    fatigue: 0,
    currentHp: 280,
    maxHp: 280,
    isInjured: false,
    statProfileId: 'hero-tank',
    statSnapshot: { hp: 280 },
    statTags: ['fortitude', 'warden'],
    isHero: true,
    survivalCount: 7,
    survivalScore: 540,
    lastUpdated: DEFAULT_TIMESTAMP,
  },
  {
    id: 'hero-salvatrice',
    name: 'Salvatrice',
    aiBehavior: 'support',
    statBlock: createStatBlock({
      hp: 210,
      damage: 18,
      txc: 28,
      evasion: 8,
      agility: 60,
      ward: 24,
      regen: 9,
      resistance: 20,
    }),
    equippedSpellIds: [],
    visualProfileId: 'hero-support',
    status: 'available',
    fatigue: 0,
    currentHp: 210,
    maxHp: 210,
    isInjured: false,
    statProfileId: 'hero-support',
    statSnapshot: { hp: 210 },
    statTags: ['ward', 'clarity'],
    isHero: true,
    survivalCount: 6,
    survivalScore: 420,
    lastUpdated: DEFAULT_TIMESTAMP,
  },
  {
    id: 'hero-giggiolillo',
    name: 'Giggiolillo',
    aiBehavior: 'dps',
    statBlock: createStatBlock({
      hp: 195,
      damage: 34,
      txc: 30,
      evasion: 12,
      agility: 72,
      critChance: 12,
      critMult: 2.1,
      movementSpeed: 125,
    }),
    equippedSpellIds: [],
    visualProfileId: 'hero-assassin',
    status: 'available',
    fatigue: 0,
    currentHp: 195,
    maxHp: 195,
    isInjured: false,
    statProfileId: 'hero-assassin',
    statSnapshot: { hp: 195 },
    statTags: ['edge', 'precision'],
    isHero: true,
    survivalCount: 5,
    survivalScore: 360,
    lastUpdated: DEFAULT_TIMESTAMP,
  },
];
