#!/usr/bin/env tsx

/**
 * Minimal Evidence Packager CLI
 *
 * CLI tool to aggregate lint/test/build output for Minimal Gameplay prompts
 * and generate evidence bundles with checksum validation.
 *
 * Usage: npm run minimal-evidence-packager -- --prompt <ID> --lint <lint.txt> --test <test.txt> --build <build.txt> [--notes <text>]
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import { createHash } from 'crypto';

interface EvidencePackagerOptions {
  prompt: string;
  lint: string;
  test: string;
  build: string;
  notes?: string;
}

interface EvidenceData {
  prompt: string;
  timestamp: string;
  checksum: string;
  files: {
    lint: FileData;
    test: FileData;
    build: FileData;
  };
  metadata: {
    totalSize: number;
    commandSummary: string;
    notes?: string;
  };
}

interface FileData {
  path: string;
  size: number;
  checksum: string;
  content: string;
}

/**
 * Generate SHA256 checksum for content.
 */
function generateChecksum(content: string): string {
  return createHash('sha256').update(content).digest('hex');
}

/**
 * Read and validate a file, returning file data.
 */
function readEvidenceFile(filePath: string, label: string): FileData {
  if (!existsSync(filePath)) {
    throw new Error(`Required ${label} file not found: ${filePath}`);
  }

  const content = readFileSync(filePath, 'utf-8');
  const checksum = generateChecksum(content);

  return {
    path: filePath,
    size: content.length,
    checksum,
    content,
  };
}

/**
 * Generate markdown report from evidence data.
 */
function generateMarkdownReport(data: EvidenceData): string {
  const { prompt, timestamp, checksum, files, metadata } = data;

  let report = `# Evidence Report: ${prompt}

**Generated:** ${timestamp}
**Overall Checksum:** \`${checksum}\`

## Summary

- **Total Size:** ${metadata.totalSize} characters
- **Command:** ${metadata.commandSummary}

## Files

### Lint Output
- **Path:** \`${files.lint.path}\`
- **Size:** ${files.lint.size} characters
- **Checksum:** \`${files.lint.checksum}\`

### Test Output
- **Path:** \`${files.test.path}\`
- **Size:** ${files.test.size} characters
- **Checksum:** \`${files.test.checksum}\`

### Build Output
- **Path:** \`${files.build.path}\`
- **Size:** ${files.build.size} characters
- **Checksum:** \`${files.build.checksum}\`

`;

  if (metadata.notes) {
    report += `## Notes

${metadata.notes}

`;
  }

  report += `## Validation

This evidence package was generated by the Minimal Evidence Packager CLI.
All files have been validated for existence and integrity.

---
*Generated by NP-MIN-PLAN-204 – Minimal Evidence Packager CLI*
`;

  return report;
}

/**
 * Package evidence from lint/test/build outputs.
 */
async function packageEvidence(options: EvidencePackagerOptions): Promise<EvidenceData> {
  const { prompt, lint, test, build, notes } = options;

  console.log(`📦 Packaging evidence for prompt: ${prompt}`);

  // Read and validate all input files
  console.log('📖 Reading input files...');
  const lintData = readEvidenceFile(lint, 'lint');
  const testData = readEvidenceFile(test, 'test');
  const buildData = readEvidenceFile(build, 'build');

  const totalSize = lintData.size + testData.size + buildData.size;

  // Create evidence data structure
  const evidenceData: EvidenceData = {
    prompt,
    timestamp: new Date().toISOString(),
    checksum: '',
    files: {
      lint: lintData,
      test: testData,
      build: buildData,
    },
    metadata: {
      totalSize,
      commandSummary: `npm run lint && npm run test && npm run build:check`,
      notes,
    },
  };

  // Generate overall checksum
  const overallContent = JSON.stringify({
    prompt,
    timestamp: evidenceData.timestamp,
    files: {
      lint: { path: lintData.path, checksum: lintData.checksum },
      test: { path: testData.path, checksum: testData.checksum },
      build: { path: buildData.path, checksum: buildData.checksum },
    },
    metadata: evidenceData.metadata,
  });

  evidenceData.checksum = generateChecksum(overallContent);

  return evidenceData;
}

/**
 * Save evidence package to files.
 */
function saveEvidencePackage(data: EvidenceData): { jsonPath: string; markdownPath: string } {
  const baseName = `${data.prompt}-evidence`;
  const jsonPath = join(process.cwd(), 'test-results', `${baseName}.json`);
  const markdownPath = join(process.cwd(), 'test-results', `${baseName}.md`);

  console.log('💾 Saving evidence files...');

  // Save JSON
  writeFileSync(jsonPath, JSON.stringify(data, null, 2));
  console.log(`✅ JSON saved: ${jsonPath}`);

  // Save Markdown
  const markdown = generateMarkdownReport(data);
  writeFileSync(markdownPath, markdown);
  console.log(`✅ Markdown saved: ${markdownPath}`);

  return { jsonPath, markdownPath };
}

/**
 * Main CLI function.
 */
async function main() {
  const args = process.argv.slice(2);

  // Parse command line arguments
  const options: Partial<EvidencePackagerOptions> = {};

  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
      case '--prompt':
        options.prompt = args[++i];
        break;
      case '--lint':
        options.lint = args[++i];
        break;
      case '--test':
        options.test = args[++i];
        break;
      case '--build':
        options.build = args[++i];
        break;
      case '--notes':
        options.notes = args[++i];
        break;
      case '--help':
      case '-h':
        console.log(`
Minimal Evidence Packager CLI

Usage: npm run minimal-evidence-packager -- --prompt <ID> --lint <lint.txt> --test <test.txt> --build <build.txt> [--notes <text>]

Required Arguments:
  --prompt <ID>        Prompt identifier (e.g., NP-MIN-STRAT-001)
  --lint <file>        Path to lint output file
  --test <file>        Path to test output file
  --build <file>       Path to build output file

Optional Arguments:
  --notes <text>       Additional notes to include in Markdown report
  --help, -h          Show this help message

Output:
  Creates <prompt>-evidence.json and <prompt>-evidence.md in test-results/

Examples:
  npm run minimal-evidence-packager -- --prompt NP-MIN-STRAT-001 --lint lint.log --test test.log --build build.log
  npm run minimal-evidence-packager -- --prompt NP-MIN-STRAT-001 --lint lint.log --test test.log --build build.log --notes "All tests passed"
`);
        process.exit(0);
        break;
      default:
        if (args[i].startsWith('-')) {
          console.error(`Unknown option: ${args[i]}`);
          process.exit(1);
        }
    }
  }

  // Validate required arguments
  if (!options.prompt || !options.lint || !options.test || !options.build) {
    console.error('Error: Missing required arguments. Use --help for usage information.');
    console.error('Required: --prompt, --lint, --test, --build');
    process.exit(1);
  }

  try {
    // Package evidence
    const evidenceData = await packageEvidence(options as EvidencePackagerOptions);

    // Save to files
    const { jsonPath, markdownPath } = saveEvidencePackage(evidenceData);

    console.log('\n🎉 Evidence packaging complete!');
    console.log(`📊 Prompt: ${evidenceData.prompt}`);
    console.log(`🔐 Checksum: ${evidenceData.checksum}`);
    console.log(`📁 JSON: ${jsonPath}`);
    console.log(`📄 Markdown: ${markdownPath}`);

  } catch (error) {
    console.error('❌ Evidence packaging failed:', error instanceof Error ? error.message : error);
    process.exit(1);
  }
}

// Run CLI if this file is executed directly
if (require.main === module) {
  main().catch((error) => {
    console.error('CLI execution failed:', error);
    process.exit(1);
  });
}

export { packageEvidence, generateMarkdownReport, EvidencePackagerOptions, EvidenceData };
