import { z } from 'zod';
import { PlaytestEventTypeSchema, type PlaytestEventType } from './playtestConfig';

/**
 * Annotation severity levels available to the assistant UI.
 */
export const AnnotationSeveritySchema = z.enum(['info', 'issue', 'blocker']);

export type AnnotationSeverity = z.infer<typeof AnnotationSeveritySchema>;

/**
 * Annotation tag definition used for quick tagging controls.
 */
export const AnnotationTagSchema = z.object({
  id: z.string(),
  label: z.string(),
  color: z.string().default('#94a3b8'),
  icon: z.string().optional(),
  shortcut: z.string().optional(),
  description: z.string().optional(),
});

export type AnnotationTag = z.infer<typeof AnnotationTagSchema>;

/**
 * Quick note chip definition, optionally preloading tags.
 */
export const QuickNoteSchema = z.object({
  id: z.string(),
  label: z.string(),
  template: z.string(),
  tags: z.array(z.string()).default([]),
});

export type QuickNoteTemplate = z.infer<typeof QuickNoteSchema>;

const TimelineSettingsSchema = z.object({
  refreshIntervalMs: z.number().min(250).max(5000).default(1000),
  maxVisibleEvents: z.number().min(5).max(200).default(80),
  markerSizePx: z.number().min(4).max(18).default(8),
  showEventTypeLegend: z.boolean().default(true),
});

const MarkdownSettingsSchema = z.object({
  headingLevel: z.number().min(1).max(6).default(3),
  includeSummary: z.boolean().default(true),
  includeTimeline: z.boolean().default(true),
  includeDeviceInfo: z.boolean().default(true),
  includePerformance: z.boolean().default(false),
  footnote: z.string().optional(),
});

const SeverityStyleSchema = z.object({
  label: z.string(),
  color: z.string(),
  accent: z.string(),
});

const SeverityRecordSchema = z.record(AnnotationSeveritySchema, SeverityStyleSchema);

const eventTaggingShape = PlaytestEventTypeSchema.options.reduce(
  (shape, eventType) => {
    shape[eventType] = z.array(z.string()).optional();
    return shape;
  },
  {} as Record<PlaytestEventType, z.ZodOptional<z.ZodArray<z.ZodString>>>,
);

const EventTaggingRulesSchema = z
  .object(eventTaggingShape)
  .partial()
  .transform((value) => value as Partial<Record<PlaytestEventType, string[]>>)
  .default({});

export type SeverityStyle = z.infer<typeof SeverityStyleSchema>;

export interface AnnotationAssistantConfig {
  tags: AnnotationTag[];
  quickNotes: QuickNoteTemplate[];
  severities: Record<AnnotationSeverity, SeverityStyle>;
  timeline: z.infer<typeof TimelineSettingsSchema>;
  markdown: z.infer<typeof MarkdownSettingsSchema>;
  eventTaggingRules: Partial<Record<PlaytestEventType, string[]>>;
}

export const AnnotationAssistantConfigSchema = z.object({
  tags: z.array(AnnotationTagSchema),
  quickNotes: z.array(QuickNoteSchema),
  severities: SeverityRecordSchema,
  timeline: TimelineSettingsSchema,
  markdown: MarkdownSettingsSchema,
  eventTaggingRules: EventTaggingRulesSchema,
});

const defaultConfigInput = {
  tags: [
    { id: 'ftue', label: 'FTUE', color: '#38bdf8', icon: '🎯' },
    { id: 'input', label: 'Input Lag', color: '#fbbf24', icon: '⚡' },
    { id: 'crash', label: 'Crash', color: '#f87171', icon: '💥' },
    { id: 'ui', label: 'UI Blocker', color: '#c084fc', icon: '🧊' },
    { id: 'copy', label: 'Copywriting', color: '#f472b6', icon: '✍️' },
  ],
  quickNotes: [
    { id: 'confusion', label: 'Confusion Spike', template: 'Player confused about objective', tags: ['ftue'] },
    { id: 'delay', label: '+250ms Input', template: 'Input feels delayed >250ms on mobile build', tags: ['input'] },
    { id: 'crash', label: 'Crash Loop', template: 'Crash observed when completing match', tags: ['crash'] },
    { id: 'text', label: 'Text Polish', template: 'Copy requires localization polish', tags: ['copy'] },
  ],
  severities: {
    info: { label: 'Info', color: '#38bdf8', accent: 'rgba(56, 189, 248, 0.16)' },
    issue: { label: 'Issue', color: '#fbbf24', accent: 'rgba(251, 191, 36, 0.18)' },
    blocker: { label: 'Blocker', color: '#f87171', accent: 'rgba(248, 113, 113, 0.2)' },
  },
  timeline: {
    refreshIntervalMs: 1000,
    maxVisibleEvents: 80,
    markerSizePx: 8,
    showEventTypeLegend: true,
  },
  markdown: {
    headingLevel: 3,
    includeSummary: true,
    includeTimeline: true,
    includeDeviceInfo: true,
    includePerformance: false,
    footnote: 'Generated by Punch Club Playtest Annotation Assistant.',
  },
  eventTaggingRules: {
    error: ['crash'],
    crash: ['crash', 'issue'],
    navigation: ['ftue'],
    tap: ['input'],
  },
} satisfies AnnotationAssistantConfig;

export const DEFAULT_ANNOTATION_ASSISTANT_CONFIG: AnnotationAssistantConfig =
  AnnotationAssistantConfigSchema.parse(defaultConfigInput);

/**
 * Merge helper guaranteeing defaults for optional consumer overrides.
 */
export function mergeAnnotationConfig(
  overrides?: Partial<AnnotationAssistantConfig>,
): AnnotationAssistantConfig {
  if (!overrides) {
    return DEFAULT_ANNOTATION_ASSISTANT_CONFIG;
  }

  return {
    ...DEFAULT_ANNOTATION_ASSISTANT_CONFIG,
    ...overrides,
    tags: overrides.tags ?? DEFAULT_ANNOTATION_ASSISTANT_CONFIG.tags,
    quickNotes: overrides.quickNotes ?? DEFAULT_ANNOTATION_ASSISTANT_CONFIG.quickNotes,
    severities: {
      ...DEFAULT_ANNOTATION_ASSISTANT_CONFIG.severities,
      ...(overrides.severities ?? {}),
    },
    timeline: {
      ...DEFAULT_ANNOTATION_ASSISTANT_CONFIG.timeline,
      ...(overrides.timeline ?? {}),
    },
    markdown: {
      ...DEFAULT_ANNOTATION_ASSISTANT_CONFIG.markdown,
      ...(overrides.markdown ?? {}),
    },
    eventTaggingRules: {
      ...DEFAULT_ANNOTATION_ASSISTANT_CONFIG.eventTaggingRules,
      ...(overrides.eventTaggingRules ?? {}),
    },
  };
}
