import type { BalancerConfig, StatDefinition, CardDefinition, BalancerPreset } from './types';

export const CORE_STATS: Record<string, StatDefinition> = {
  hp: {
    id: 'hp',
    label: 'Hit Points',
    description: 'Total health pool',
    type: 'number',
    min: 10,
    max: 2000,
    step: 10,
    defaultValue: 150,
    weight: 1.0,
    isCore: true,
    isDerived: false,
    isLocked: false,
    isHidden: false,
  },
  damage: {
    id: 'damage',
    label: 'Damage',
    description: 'Base damage per attack',
    type: 'number',
    min: 1,
    max: 500,
    step: 0.1,
    defaultValue: 35.7,
    weight: 5.0,
    isCore: true,
    isDerived: false,
    isLocked: false,
    isHidden: false,
  },
  htk: {
    id: 'htk',
    label: 'Hits to Kill',
    description: 'Number of hits needed to defeat target',
    type: 'number',
    min: 1,
    max: 50,
    step: 0.1,
    defaultValue: 4.2,
    weight: 0,
    isCore: true,
    isDerived: true,
    formula: 'hp / damage',
    bgColor: 'bg-orange-500/10',
    isLocked: false,
    isHidden: true,
  },
};

export const CORE_CARD: CardDefinition = {
  id: 'core',
  title: 'Core Profile',
  color: 'text-amber-300',
  icon: '⚔️',
  statIds: ['hp', 'damage', 'htk'],
  isCore: true,
  order: 0,
};

const ADDITIONAL_STATS: Record<string, StatDefinition> = {
  txc: {
    id: 'txc',
    label: 'TxC',
    description: 'Attack roll accuracy',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: 25,
    weight: 1,
    isCore: false,
    isDerived: false,
    isLocked: false,
    isHidden: false,
  },
  evasion: {
    id: 'evasion',
    label: 'Evasion',
    description: 'Avoidance against TxC',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: 0,
    weight: 1,
    isCore: false,
    isDerived: false,
  },
  hitChance: {
    id: 'hitChance',
    label: 'Hit Chance %',
    description: 'Final chance to hit',
    type: 'percentage',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: 75,
    weight: 0,
    isCore: false,
    isDerived: true,
    formula: 'txc - evasion',
    isHidden: true,
  },
  attacksPerKo: {
    id: 'attacksPerKo',
    label: 'Attacks per KO',
    description: 'Average attacks to defeat the target',
    type: 'number',
    min: 1,
    max: 100,
    step: 0.1,
    defaultValue: 5.3,
    weight: 0,
    isCore: false,
    isDerived: true,
    formula: 'htk / hitChance',
    isHidden: true,
  },
  critChance: {
    id: 'critChance',
    label: 'Crit Chance %',
    description: 'Probability of critical hit',
    type: 'percentage',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: 5,
    weight: 1,
    isCore: false,
    isDerived: false,
  },
  critMult: {
    id: 'critMult',
    label: 'Crit Multiplier',
    description: 'Damage multiplier on crit',
    type: 'number',
    min: 1,
    max: 5,
    step: 0.1,
    defaultValue: 2,
    weight: 1,
    isCore: false,
    isDerived: false,
  },
  critTxCBonus: {
    id: 'critTxCBonus',
    label: 'Crit TxC Bonus',
    description: 'Bonus accuracy on crit confirm',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: 20,
    weight: 1,
    isCore: false,
    isDerived: false,
  },
  failChance: {
    id: 'failChance',
    label: 'Fail Chance %',
    description: 'Probability of failure',
    type: 'percentage',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: 0,
    weight: 1,
    isCore: false,
    isDerived: false,
  },
  failMult: {
    id: 'failMult',
    label: 'Fail Multiplier',
    description: 'Damage multiplier on failure',
    type: 'number',
    min: 0,
    max: 1,
    step: 0.1,
    defaultValue: 0,
    weight: 1,
    isCore: false,
    isDerived: false,
  },
  failTxCMalus: {
    id: 'failTxCMalus',
    label: 'Fail TxC Malus',
    description: 'Penalty applied on failure',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: 20,
    weight: 1,
    isCore: false,
    isDerived: false,
  },
  ward: {
    id: 'ward',
    label: 'Armor (Flat)',
    description: 'Flat damage mitigation',
    type: 'number',
    min: 0,
    max: 500,
    step: 10,
    defaultValue: 0,
    weight: 1,
    isCore: false,
    isDerived: false,
  },
  armor: {
    id: 'armor',
    label: 'Armor %',
    description: 'Percent damage reduction',
    type: 'percentage',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: 0,
    weight: 1,
    isCore: false,
    isDerived: false,
  },
  resistance: {
    id: 'resistance',
    label: 'Resistance %',
    description: 'Secondary reduction',
    type: 'percentage',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: 0,
    weight: 1,
    isCore: false,
    isDerived: false,
  },
  armorPen: {
    id: 'armorPen',
    label: 'Armor Penetration',
    description: 'Flat armor ignored',
    type: 'number',
    min: 0,
    max: 200,
    step: 1,
    defaultValue: 0,
    weight: 1,
    isCore: false,
    isDerived: false,
  },
  penPercent: {
    id: 'penPercent',
    label: 'Penetration %',
    description: 'Percent resistance ignored',
    type: 'percentage',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: 0,
    weight: 1,
    isCore: false,
    isDerived: false,
  },
  effectiveDamage: {
    id: 'effectiveDamage',
    label: 'Effective Damage',
    description: 'Damage after mitigation',
    type: 'number',
    min: 1,
    max: 500,
    step: 0.1,
    defaultValue: 35.7,
    weight: 0,
    isCore: false,
    isDerived: true,
    formula: 'damage * (1 - armor/100) - ward',
    isHidden: true,
  },
  lifesteal: {
    id: 'lifesteal',
    label: 'Lifesteal %',
    description: 'Percent of damage returned as HP',
    type: 'percentage',
    min: 0,
    max: 100,
    step: 1,
    defaultValue: 0,
    weight: 1,
    isCore: false,
    isDerived: false,
  },
  regen: {
    id: 'regen',
    label: 'Regeneration',
    description: 'HP recovered per turn',
    type: 'number',
    min: 0,
    max: 500,
    step: 1,
    defaultValue: 0,
    weight: 1,
    isCore: false,
    isDerived: false,
  },
  ttk: {
    id: 'ttk',
    label: 'TTK',
    description: 'Time to kill (turns)',
    type: 'number',
    min: 0.1,
    max: 200,
    step: 0.1,
    defaultValue: 4,
    weight: 0,
    isCore: false,
    isDerived: true,
    formula: 'hp / effectiveDamage',
    isHidden: true,
  },
  edpt: {
    id: 'edpt',
    label: 'EDPT',
    description: 'Effective damage per turn',
    type: 'number',
    min: 0,
    max: 2000,
    step: 1,
    defaultValue: 37.5,
    weight: 0,
    isCore: false,
    isDerived: true,
    formula: 'effectiveDamage * hitChance / 100',
    isHidden: true,
  },
  earlyImpact: {
    id: 'earlyImpact',
    label: 'Early Impact',
    description: 'Damage in first 3 turns',
    type: 'number',
    min: 0,
    max: 6000,
    step: 1,
    defaultValue: 112.5,
    weight: 0,
    isCore: false,
    isDerived: true,
    formula: 'edpt * 3',
    isHidden: true,
  },
};

const DEFAULT_CARDS: Record<string, CardDefinition> = {
  core: CORE_CARD,
  txcHarmony: {
    id: 'txcHarmony',
    title: 'Hit Harmony',
    color: 'text-cyan-300',
    icon: '🎯',
    statIds: ['txc', 'evasion', 'hitChance', 'attacksPerKo'],
    isCore: false,
    order: 1,
    isLocked: false,
    isHidden: false,
  },
  criticalEquilibrium: {
    id: 'criticalEquilibrium',
    title: 'Critical Equilibrium',
    color: 'text-rose-300',
    icon: '✦',
    statIds: ['critChance', 'critMult', 'critTxCBonus', 'failChance', 'failMult', 'failTxCMalus'],
    isCore: false,
    order: 2,
    isLocked: false,
    isHidden: false,
  },
  mitigationPen: {
    id: 'mitigationPen',
    title: 'Mitigation & Pen',
    color: 'text-emerald-300',
    icon: '🛡️',
    statIds: ['ward', 'armor', 'resistance', 'armorPen', 'penPercent', 'effectiveDamage'],
    isCore: false,
    order: 3,
    isLocked: false,
    isHidden: false,
  },
  sustain: {
    id: 'sustain',
    title: 'Sustain',
    color: 'text-green-300',
    icon: '🌿',
    statIds: ['lifesteal', 'regen'],
    isCore: false,
    order: 4,
    isLocked: false,
    isHidden: false,
  },
  combatMetrics: {
    id: 'combatMetrics',
    title: 'Combat Metrics',
    color: 'text-purple-300',
    icon: '📊',
    statIds: ['ttk', 'edpt', 'earlyImpact'],
    isCore: false,
    order: 5,
    isLocked: false,
    isHidden: false,
  },
};

export const DEFAULT_PRESET: BalancerPreset = {
  id: 'standard',
  name: 'Standard',
  description: 'Default balanced weights',
  weights: {
    hp: 1.0,
    damage: 5.0,
    htk: 0,
  },
  isBuiltIn: true,
  createdAt: '2025-01-01T00:00:00Z',
  modifiedAt: '2025-01-01T00:00:00Z',
};

export const DEFAULT_CONFIG: BalancerConfig = {
  version: '1.0.0',
  stats: { ...CORE_STATS, ...ADDITIONAL_STATS },
  cards: DEFAULT_CARDS,
  presets: { standard: DEFAULT_PRESET },
  activePresetId: 'standard',
};

export function isCoreStat(statId: string): boolean {
  return Object.prototype.hasOwnProperty.call(CORE_STATS, statId);
}

export function isCoreCard(cardId: string): boolean {
  return cardId === 'core';
}
