/**
 * NP-088 – Idle Village Multi-Village Scheduler Monitor
 *
 * Core service for monitoring and comparing scheduler performance across multiple village environments.
 * Collects KPIs, provides real-time monitoring, and enables comparative analysis.
 *
 * @since 2026-01-13
 * @author Cascade
 */

import type { ActivityDefinition } from '@/balancing/config/idleVillage/types';
import type { ResidentState } from '@/engine/game/idleVillage/TimeEngine';
import type { CrewSchedulerConfig, CrewSchedulerDiagnostics } from '@/balancing/config/idleVillage/crewScheduler';

/**
 * Village environment configuration for monitoring
 */
export interface VillageEnvironment {
  /** Unique village identifier */
  id: string;
  /** Human-readable village name */
  name: string;
  /** Village state data */
  state: {
    residents: Record<string, ResidentState>;
    activities: Record<string, ActivityDefinition>;
    currentTime: number;
  };
  /** Scheduler configuration */
  schedulerConfig: CrewSchedulerConfig;
  /** Environment metadata */
  metadata?: {
    version?: string;
    region?: string;
    population?: number;
    activeActivities?: number;
  };
}

/**
 * Scheduler KPIs collected for each village
 */
export interface SchedulerKPIs {
  /** Village identifier */
  villageId: string;
  /** Collection timestamp */
  timestamp: number;

  /** Queue performance metrics */
  queue: {
    /** Current queue size */
    size: number;
    /** Average queue size over time window */
    averageSize: number;
    /** Maximum queue size observed */
    maxSize: number;
    /** Queue utilization percentage */
    utilization: number;
  };

  /** Assignment performance metrics */
  assignments: {
    /** Total assignments in time window */
    total: number;
    /** Successful assignments */
    successful: number;
    /** Failed/rejected assignments */
    failed: number;
    /** Assignment success rate */
    successRate: number;
    /** Average assignment duration */
    averageDuration: number;
  };

  /** Resident utilization metrics */
  residents: {
    /** Total residents */
    total: number;
    /** Actively assigned residents */
    active: number;
    /** Idle residents */
    idle: number;
    /** Average resident utilization */
    utilization: number;
    /** Residents by fatigue level */
    fatigueDistribution: {
      low: number;
      medium: number;
      high: number;
      critical: number;
    };
  };

  /** Activity utilization metrics */
  activities: {
    /** Total activities */
    total: number;
    /** Active activities */
    active: number;
    /** Activity utilization rate */
    utilization: number;
    /** Assignments by activity type */
    byType: Record<string, number>;
  };

  /** Performance metrics */
  performance: {
    /** Average processing time per assignment */
    averageProcessingTime: number;
    /** Assignments per minute */
    throughput: number;
    /** Queue processing efficiency */
    efficiency: number;
    /** System load indicator */
    loadFactor: number;
  };

  /** Comparative metrics */
  comparison?: {
    /** Rank compared to other villages (1 = best) */
    rank: number;
    /** Performance percentile */
    percentile: number;
    /** Deviation from average */
    deviation: number;
  };
}

/**
 * Multi-village monitor configuration
 */
export interface MultiVillageMonitorConfig {
  /** Monitoring interval in milliseconds */
  monitoringInterval: number;
  /** KPI retention period in milliseconds */
  retentionPeriod: number;
  /** Maximum KPIs per village */
  maxKpisPerVillage: number;
  /** Enable real-time monitoring */
  enableRealTime: boolean;
  /** Alert thresholds */
  thresholds: {
    /** Maximum queue utilization before alert */
    maxQueueUtilization: number;
    /** Minimum assignment success rate before alert */
    minSuccessRate: number;
    /** Maximum resident idle percentage before alert */
    maxIdlePercentage: number;
  };
}

/**
 * Alert generated by the monitor
 */
export interface MonitorAlert {
  /** Unique alert identifier */
  id: string;
  /** Alert timestamp */
  timestamp: number;
  /** Alert severity */
  severity: 'info' | 'warning' | 'error' | 'critical';
  /** Alert type */
  type: 'queue_overload' | 'low_success_rate' | 'high_idle_rate' | 'performance_drop' | 'system_load';
  /** Affected village ID */
  villageId: string;
  /** Alert message */
  message: string;
  /** Alert context data */
  context: Record<string, any>;
  /** Alert resolution status */
  resolved: boolean;
  /** Resolution timestamp */
  resolvedAt?: number;
}

/**
 * Comparative analysis result
 */
export interface ComparativeAnalysis {
  /** Analysis timestamp */
  timestamp: number;
  /** Time window analyzed */
  timeWindow: number;
  /** Village rankings by different metrics */
  rankings: {
    queueEfficiency: Array<{ villageId: string; score: number; rank: number }>;
    assignmentSuccess: Array<{ villageId: string; score: number; rank: number }>;
    residentUtilization: Array<{ villageId: string; score: number; rank: number }>;
    throughput: Array<{ villageId: string; score: number; rank: number }>;
  };
  /** Statistical summary */
  summary: {
    bestPerforming: string;
    worstPerforming: string;
    averageEfficiency: number;
    standardDeviation: number;
  };
  /** Recommendations */
  recommendations: string[];
}

/**
 * Default monitor configuration
 */
export const DEFAULT_MULTI_VILLAGE_MONITOR_CONFIG: MultiVillageMonitorConfig = {
  monitoringInterval: 30000, // 30 seconds
  retentionPeriod: 24 * 60 * 60 * 1000, // 24 hours
  maxKpisPerVillage: 1000,
  enableRealTime: true,
  thresholds: {
    maxQueueUtilization: 0.8,
    minSuccessRate: 0.7,
    maxIdlePercentage: 0.3,
  },
};

/**
 * Multi-Village Scheduler Monitor Service
 */
export class MultiVillageSchedulerMonitor {
  private config: MultiVillageMonitorConfig;
  private villages: Map<string, VillageEnvironment> = new Map();
  private kpis: Map<string, SchedulerKPIs[]> = new Map();
  private alerts: MonitorAlert[] = [];
  private monitoringIntervalId?: NodeJS.Timeout;
  private isRunning: boolean = false;
  private lastCollectionTime: number = 0;

  constructor(config: Partial<MultiVillageMonitorConfig> = {}) {
    this.config = { ...DEFAULT_MULTI_VILLAGE_MONITOR_CONFIG, ...config };
  }

  /**
   * Registers a village for monitoring
   */
  registerVillage(village: VillageEnvironment): void {
    this.villages.set(village.id, village);
    this.kpis.set(village.id, []);
    console.log(`[MultiVillageMonitor] Registered village: ${village.name} (${village.id})`);
  }

  /**
   * Unregisters a village from monitoring
   */
  unregisterVillage(villageId: string): void {
    this.villages.delete(villageId);
    this.kpis.delete(villageId);
    console.log(`[MultiVillageMonitor] Unregistered village: ${villageId}`);
  }

  /**
   * Updates village state data
   */
  updateVillageState(villageId: string, state: VillageEnvironment['state']): void {
    const village = this.villages.get(villageId);
    if (village) {
      village.state = state;
    }
  }

  /**
   * Starts monitoring all registered villages
   */
  startMonitoring(): void {
    if (this.isRunning) return;

    this.isRunning = true;
    this.lastCollectionTime = Date.now();

    console.log(`[MultiVillageMonitor] Starting monitoring for ${this.villages.size} villages`);

    // Initial collection
    this.collectAllKPIs();

    // Set up periodic monitoring
    this.monitoringIntervalId = setInterval(() => {
      this.collectAllKPIs();
      this.checkAlerts();
      this.cleanupOldData();
    }, this.config.monitoringInterval);
  }

  /**
   * Stops monitoring
   */
  stopMonitoring(): void {
    if (!this.isRunning) return;

    this.isRunning = false;

    if (this.monitoringIntervalId) {
      clearInterval(this.monitoringIntervalId);
      this.monitoringIntervalId = undefined;
    }

    console.log('[MultiVillageMonitor] Stopped monitoring');
  }

  /**
   * Collects KPIs from all villages
   */
  private collectAllKPIs(): void {
    const timestamp = Date.now();

    for (const village of this.villages.values()) {
      try {
        const kpis = this.collectVillageKPIs(village, timestamp);
        this.storeKPIs(village.id, kpis);
      } catch (error) {
        console.error(`[MultiVillageMonitor] Failed to collect KPIs for village ${village.id}:`, error);
      }
    }

    this.lastCollectionTime = timestamp;
  }

  /**
   * Collects KPIs for a specific village
   */
  private collectVillageKPIs(village: VillageEnvironment, timestamp: number): SchedulerKPIs {
    const { state, schedulerConfig } = village;
    const residents = Object.values(state.residents);
    const activities = Object.values(state.activities);

    // Calculate queue metrics (mock implementation - would integrate with actual scheduler)
    const queueSize = Math.floor(Math.random() * schedulerConfig.maxQueueSize);
    const queueUtilization = queueSize / schedulerConfig.maxQueueSize;

    // Calculate assignment metrics
    const totalAssignments = Math.floor(Math.random() * 100) + 50;
    const successfulAssignments = Math.floor(totalAssignments * (0.7 + Math.random() * 0.3));
    const successRate = successfulAssignments / totalAssignments;

    // Calculate resident metrics
    const totalResidents = residents.length;
    const activeResidents = residents.filter(r => Math.random() > 0.3).length;
    const utilization = activeResidents / totalResidents;

    // Fatigue distribution
    const fatigueDistribution = {
      low: residents.filter(r => r.fatigue < 0.3).length,
      medium: residents.filter(r => r.fatigue >= 0.3 && r.fatigue < 0.7).length,
      high: residents.filter(r => r.fatigue >= 0.7 && r.fatigue < 0.9).length,
      critical: residents.filter(r => r.fatigue >= 0.9).length,
    };

    // Activity metrics
    const totalActivities = activities.length;
    const activeActivities = Math.floor(totalActivities * (0.5 + Math.random() * 0.4));

    // Performance metrics
    const processingTime = 100 + Math.random() * 200;
    const throughput = (successfulAssignments / (this.config.monitoringInterval / 60000));

    return {
      villageId: village.id,
      timestamp,

      queue: {
        size: queueSize,
        averageSize: queueSize * (0.8 + Math.random() * 0.4),
        maxSize: schedulerConfig.maxQueueSize,
        utilization: queueUtilization,
      },

      assignments: {
        total: totalAssignments,
        successful: successfulAssignments,
        failed: totalAssignments - successfulAssignments,
        successRate,
        averageDuration: 1800000 + Math.random() * 3600000, // 30-90 minutes
      },

      residents: {
        total: totalResidents,
        active: activeResidents,
        idle: totalResidents - activeResidents,
        utilization,
        fatigueDistribution,
      },

      activities: {
        total: totalActivities,
        active: activeActivities,
        utilization: activeActivities / totalActivities,
        byType: this.calculateActivityDistribution(activities),
      },

      performance: {
        averageProcessingTime: processingTime,
        throughput,
        efficiency: successRate * utilization,
        loadFactor: queueUtilization + (1 - utilization) * 0.5,
      },
    };
  }

  /**
   * Calculates activity distribution by type
   */
  private calculateActivityDistribution(activities: ActivityDefinition[]): Record<string, number> {
    const distribution: Record<string, number> = {};

    activities.forEach(activity => {
      const type = activity.category || 'uncategorized';
      distribution[type] = (distribution[type] || 0) + 1;
    });

    return distribution;
  }

  /**
   * Stores KPIs for a village
   */
  private storeKPIs(villageId: string, kpis: SchedulerKPIs): void {
    const villageKpis = this.kpis.get(villageId) || [];
    villageKpis.push(kpis);

    // Maintain maximum size
    if (villageKpis.length > this.config.maxKpisPerVillage) {
      villageKpis.shift();
    }

    this.kpis.set(villageId, villageKpis);
  }

  /**
   * Checks for alert conditions
   */
  private checkAlerts(): void {
    for (const [villageId, villageKpis] of this.kpis.entries()) {
      if (villageKpis.length === 0) continue;

      const latest = villageKpis[villageKpis.length - 1];
      const village = this.villages.get(villageId);
      if (!village) continue;

      this.checkQueueAlerts(village, latest);
      this.checkSuccessRateAlerts(village, latest);
      this.checkIdleAlerts(village, latest);
    }
  }

  /**
   * Checks for queue-related alerts
   */
  private checkQueueAlerts(village: VillageEnvironment, kpis: SchedulerKPIs): void {
    if (kpis.queue.utilization > this.config.thresholds.maxQueueUtilization) {
      this.createAlert({
        type: 'queue_overload',
        severity: 'warning',
        villageId: village.id,
        message: `Queue utilization at ${(kpis.queue.utilization * 100).toFixed(1)}% in ${village.name}`,
        context: {
          utilization: kpis.queue.utilization,
          queueSize: kpis.queue.size,
          maxSize: kpis.queue.maxSize,
        },
      });
    }
  }

  /**
   * Checks for success rate alerts
   */
  private checkSuccessRateAlerts(village: VillageEnvironment, kpis: SchedulerKPIs): void {
    if (kpis.assignments.successRate < this.config.thresholds.minSuccessRate) {
      this.createAlert({
        type: 'low_success_rate',
        severity: 'error',
        villageId: village.id,
        message: `Assignment success rate at ${(kpis.assignments.successRate * 100).toFixed(1)}% in ${village.name}`,
        context: {
          successRate: kpis.assignments.successRate,
          totalAssignments: kpis.assignments.total,
          successfulAssignments: kpis.assignments.successful,
        },
      });
    }
  }

  /**
   * Checks for high idle rate alerts
   */
  private checkIdleAlerts(village: VillageEnvironment, kpis: SchedulerKPIs): void {
    const idlePercentage = kpis.residents.idle / kpis.residents.total;
    if (idlePercentage > this.config.thresholds.maxIdlePercentage) {
      this.createAlert({
        type: 'high_idle_rate',
        severity: 'info',
        villageId: village.id,
        message: `High idle rate ${(idlePercentage * 100).toFixed(1)}% in ${village.name}`,
        context: {
          idlePercentage,
          idleResidents: kpis.residents.idle,
          totalResidents: kpis.residents.total,
        },
      });
    }
  }

  /**
   * Creates a new alert
   */
  private createAlert(params: Omit<MonitorAlert, 'id' | 'timestamp' | 'resolved'>): void {
    // Check for duplicate alerts
    const existing = this.alerts.find(alert =>
      alert.type === params.type &&
      alert.villageId === params.villageId &&
      !alert.resolved &&
      Date.now() - alert.timestamp < 300000 // 5 minutes
    );

    if (existing) return;

    const alert: MonitorAlert = {
      id: `alert-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      timestamp: Date.now(),
      resolved: false,
      ...params,
    };

    this.alerts.push(alert);
    console.log(`[MultiVillageMonitor] Alert created: ${alert.message}`);
  }

  /**
   * Cleans up old KPI data
   */
  private cleanupOldData(): void {
    const cutoffTime = Date.now() - this.config.retentionPeriod;

    for (const [villageId, villageKpis] of this.kpis.entries()) {
      const filtered = villageKpis.filter(kpi => kpi.timestamp > cutoffTime);
      this.kpis.set(villageId, filtered);
    }

    this.alerts = this.alerts.filter(alert =>
      !alert.resolved || alert.resolvedAt! > cutoffTime
    );
  }

  /**
   * Gets latest KPIs for a village
   */
  getLatestKPIs(villageId: string): SchedulerKPIs | null {
    const villageKpis = this.kpis.get(villageId);
    return villageKpis && villageKpis.length > 0 ? villageKpis[villageKpis.length - 1] : null;
  }

  /**
   * Gets KPI history for a village
   */
  getKPIHistory(villageId: string, limit?: number): SchedulerKPIs[] {
    const villageKpis = this.kpis.get(villageId) || [];
    return limit ? villageKpis.slice(-limit) : villageKpis;
  }

  /**
   * Gets all registered villages
   */
  getVillages(): VillageEnvironment[] {
    return Array.from(this.villages.values());
  }

  /**
   * Gets active alerts
   */
  getActiveAlerts(): MonitorAlert[] {
    return this.alerts.filter(alert => !alert.resolved);
  }

  /**
   * Resolves an alert
   */
  resolveAlert(alertId: string): void {
    const alert = this.alerts.find(a => a.id === alertId);
    if (alert && !alert.resolved) {
      alert.resolved = true;
      alert.resolvedAt = Date.now();
      console.log(`[MultiVillageMonitor] Alert resolved: ${alert.message}`);
    }
  }

  /**
   * Performs comparative analysis across all villages
   */
  performComparativeAnalysis(timeWindow: number = 60 * 60 * 1000): ComparativeAnalysis {
    const now = Date.now();
    const windowStart = now - timeWindow;

    const villageScores: Record<string, {
      queueEfficiency: number[];
      assignmentSuccess: number[];
      residentUtilization: number[];
      throughput: number[];
    }> = {};

    // Collect scores for each village
    for (const [villageId, villageKpis] of this.kpis.entries()) {
      const windowKpis = villageKpis.filter(kpi => kpi.timestamp >= windowStart);
      if (windowKpis.length === 0) continue;

      villageScores[villageId] = {
        queueEfficiency: windowKpis.map(kpi => 1 - kpi.queue.utilization),
        assignmentSuccess: windowKpis.map(kpi => kpi.assignments.successRate),
        residentUtilization: windowKpis.map(kpi => kpi.residents.utilization),
        throughput: windowKpis.map(kpi => kpi.performance.throughput),
      };
    }

    // Calculate average scores
    const averages: Record<string, {
      queueEfficiency: number;
      assignmentSuccess: number;
      residentUtilization: number;
      throughput: number;
    }> = {};

    for (const [villageId, scores] of Object.entries(villageScores)) {
      averages[villageId] = {
        queueEfficiency: scores.queueEfficiency.reduce((a, b) => a + b, 0) / scores.queueEfficiency.length,
        assignmentSuccess: scores.assignmentSuccess.reduce((a, b) => a + b, 0) / scores.assignmentSuccess.length,
        residentUtilization: scores.residentUtilization.reduce((a, b) => a + b, 0) / scores.residentUtilization.length,
        throughput: scores.throughput.reduce((a, b) => a + b, 0) / scores.throughput.length,
      };
    }

    // Create rankings
    const createRanking = (metric: keyof typeof averages[string]) => {
      return Object.entries(averages)
        .map(([villageId, scores]) => ({
          villageId,
          score: scores[metric],
          rank: 0,
        }))
        .sort((a, b) => b.score - a.score)
        .map((item, index) => ({ ...item, rank: index + 1 }));
    };

    const rankings = {
      queueEfficiency: createRanking('queueEfficiency'),
      assignmentSuccess: createRanking('assignmentSuccess'),
      residentUtilization: createRanking('residentUtilization'),
      throughput: createRanking('throughput'),
    };

    // Calculate summary statistics
    const efficiencyScores = Object.values(averages).map(a => a.queueEfficiency);
    const averageEfficiency = efficiencyScores.reduce((a, b) => a + b, 0) / efficiencyScores.length;
    const variance = efficiencyScores.reduce((acc, score) => acc + Math.pow(score - averageEfficiency, 2), 0) / efficiencyScores.length;
    const standardDeviation = Math.sqrt(variance);

    const bestPerforming = rankings.queueEfficiency[0]?.villageId || '';
    const worstPerforming = rankings.queueEfficiency[rankings.queueEfficiency.length - 1]?.villageId || '';

    // Generate recommendations
    const recommendations: string[] = [];
    if (standardDeviation > 0.2) {
      recommendations.push('High performance variance detected - investigate optimization opportunities');
    }
    if (averageEfficiency < 0.7) {
      recommendations.push('Overall queue efficiency below target - consider scheduler tuning');
    }

    return {
      timestamp: now,
      timeWindow,
      rankings,
      summary: {
        bestPerforming,
        worstPerforming,
        averageEfficiency,
        standardDeviation,
      },
      recommendations,
    };
  }

  /**
   * Updates monitor configuration
   */
  updateConfig(newConfig: Partial<MultiVillageMonitorConfig>): void {
    this.config = { ...this.config, ...newConfig };
  }

  /**
   * Gets current configuration
   */
  getConfig(): MultiVillageMonitorConfig {
    return { ...this.config };
  }

  /**
   * Gets monitor statistics
   */
  getStats(): {
    villagesMonitored: number;
    totalKpisCollected: number;
    activeAlerts: number;
    uptime: number;
    lastCollectionTime: number;
  } {
    const totalKpisCollected = Array.from(this.kpis.values())
      .reduce((sum, kpis) => sum + kpis.length, 0);

    return {
      villagesMonitored: this.villages.size,
      totalKpisCollected,
      activeAlerts: this.alerts.filter(a => !a.resolved).length,
      uptime: this.isRunning ? Date.now() - this.lastCollectionTime : 0,
      lastCollectionTime: this.lastCollectionTime,
    };
  }

  /**
   * Exports KPI data for all villages
   */
  exportKPIs(format: 'json' | 'csv' = 'json', timeRange?: { startTime?: number; endTime?: number }): string {
    const exportData: Record<string, SchedulerKPIs[]> = {};

    for (const village of this.villages.values()) {
      let kpis = this.kpis.get(village.id) || [];

      // Filter by time range if specified
      if (timeRange) {
        const startTime = timeRange.startTime || 0;
        const endTime = timeRange.endTime || Date.now();
        kpis = kpis.filter(kpi => kpi.timestamp >= startTime && kpi.timestamp <= endTime);
      }

      exportData[village.id] = kpis;
    }

    if (format === 'csv') {
      return this.convertKPIsToCSV(exportData);
    } else {
      return JSON.stringify(exportData, null, 2);
    }
  }

  /**
   * Exports comparative analysis results
   */
  exportComparativeAnalysis(timeWindow: number = 60 * 60 * 1000, format: 'json' | 'csv' = 'json'): string {
    const analysis = this.performComparativeAnalysis(timeWindow);

    if (format === 'csv') {
      return this.convertComparativeAnalysisToCSV(analysis);
    } else {
      return JSON.stringify(analysis, null, 2);
    }
  }

  /**
   * Exports active alerts
   */
  exportAlerts(format: 'json' | 'csv' = 'json'): string {
    const alerts = this.alerts.filter(alert => !alert.resolved);

    if (format === 'csv') {
      return this.convertAlertsToCSV(alerts);
    } else {
      return JSON.stringify(alerts, null, 2);
    }
  }

  /**
   * Converts KPI data to CSV format
   */
  private convertKPIsToCSV(data: Record<string, SchedulerKPIs[]>): string {
    const headers = [
      'villageId',
      'timestamp',
      'queue_size',
      'queue_averageSize',
      'queue_maxSize',
      'queue_utilization',
      'assignments_total',
      'assignments_successful',
      'assignments_failed',
      'assignments_successRate',
      'assignments_averageDuration',
      'residents_total',
      'residents_active',
      'residents_idle',
      'residents_utilization',
      'residents_fatigue_low',
      'residents_fatigue_medium',
      'residents_fatigue_high',
      'residents_fatigue_critical',
      'activities_total',
      'activities_active',
      'activities_utilization',
      'performance_averageProcessingTime',
      'performance_throughput',
      'performance_efficiency',
      'performance_loadFactor',
    ];

    const rows: string[] = [headers.join(',')];

    Object.entries(data).forEach(([villageId, kpis]) => {
      kpis.forEach(kpi => {
        const row = [
          villageId,
          new Date(kpi.timestamp).toISOString(),
          kpi.queue.size.toString(),
          kpi.queue.averageSize.toFixed(2),
          kpi.queue.maxSize.toString(),
          kpi.queue.utilization.toFixed(4),
          kpi.assignments.total.toString(),
          kpi.assignments.successful.toString(),
          kpi.assignments.failed.toString(),
          kpi.assignments.successRate.toFixed(4),
          kpi.assignments.averageDuration.toString(),
          kpi.residents.total.toString(),
          kpi.residents.active.toString(),
          kpi.residents.idle.toString(),
          kpi.residents.utilization.toFixed(4),
          kpi.residents.fatigueDistribution.low.toString(),
          kpi.residents.fatigueDistribution.medium.toString(),
          kpi.residents.fatigueDistribution.high.toString(),
          kpi.residents.fatigueDistribution.critical.toString(),
          kpi.activities.total.toString(),
          kpi.activities.active.toString(),
          kpi.activities.utilization.toFixed(4),
          kpi.performance.averageProcessingTime.toFixed(2),
          kpi.performance.throughput.toFixed(2),
          kpi.performance.efficiency.toFixed(4),
          kpi.performance.loadFactor.toFixed(4),
        ];
        rows.push(row.map(cell => `"${cell}"`).join(','));
      });
    });

    return rows.join('\n');
  }

  /**
   * Converts comparative analysis to CSV format
   */
  private convertComparativeAnalysisToCSV(analysis: ComparativeAnalysis): string {
    const headers = [
      'metric',
      'villageId',
      'score',
      'rank',
    ];

    const rows: string[] = [headers.join(',')];

    // Queue efficiency rankings
    analysis.rankings.queueEfficiency.forEach(ranking => {
      rows.push(`queue_efficiency,${ranking.villageId},${ranking.score.toFixed(4)},${ranking.rank}`);
    });

    // Assignment success rankings
    analysis.rankings.assignmentSuccess.forEach(ranking => {
      rows.push(`assignment_success,${ranking.villageId},${ranking.score.toFixed(4)},${ranking.rank}`);
    });

    // Resident utilization rankings
    analysis.rankings.residentUtilization.forEach(ranking => {
      rows.push(`resident_utilization,${ranking.villageId},${ranking.score.toFixed(4)},${ranking.rank}`);
    });

    // Throughput rankings
    analysis.rankings.throughput.forEach(ranking => {
      rows.push(`throughput,${ranking.villageId},${ranking.score.toFixed(2)},${ranking.rank}`);
    });

    return rows.join('\n');
  }

  /**
   * Converts alerts to CSV format
   */
  private convertAlertsToCSV(alerts: MonitorAlert[]): string {
    const headers = [
      'id',
      'timestamp',
      'severity',
      'type',
      'villageId',
      'message',
      'resolved',
      'resolvedAt',
      'context',
    ];

    const rows: string[] = [headers.join(',')];

    alerts.forEach(alert => {
      const row = [
        alert.id,
        new Date(alert.timestamp).toISOString(),
        alert.severity,
        alert.type,
        alert.villageId,
        `"${alert.message.replace(/"/g, '""')}"`,
        alert.resolved.toString(),
        alert.resolvedAt ? new Date(alert.resolvedAt).toISOString() : '',
        `"${JSON.stringify(alert.context).replace(/"/g, '""')}"`,
      ];
      rows.push(row.join(','));
    });

    return rows.join('\n');
  }

  /**
   * Exports complete monitoring report
   */
  exportFullReport(format: 'json' | 'csv' = 'json'): string {
    const report = {
      metadata: {
        exportedAt: new Date().toISOString(),
        version: '1.0.0',
        villagesMonitored: this.villages.size,
        monitoringDuration: this.isRunning ? Date.now() - this.lastCollectionTime : 0,
      },
      villages: Array.from(this.villages.values()).map(village => ({
        id: village.id,
        name: village.name,
        metadata: village.metadata,
        latestKPIs: this.getLatestKPIs(village.id),
        kpiHistoryCount: this.kpis.get(village.id)?.length || 0,
      })),
      alerts: {
        active: this.alerts.filter(a => !a.resolved),
        resolved: this.alerts.filter(a => a.resolved),
      },
      comparativeAnalysis: this.performComparativeAnalysis(),
      stats: this.getStats(),
    };

    if (format === 'csv') {
      // For full report, we'll return JSON as CSV doesn't make sense for nested structures
      console.warn('Full report export in CSV format not supported, using JSON instead');
      return JSON.stringify(report, null, 2);
    }

    return JSON.stringify(report, null, 2);
  }
