import React from 'react';
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, fireEvent, within } from '@testing-library/react';

import { PlaytestAnnotationAssistant } from '@/ui/playtest/PlaytestAnnotationAssistant';
import type { PlaytestAnnotation } from '@/ui/playtest/PlaytestAnnotationAssistant.helpers';
import { buildAnnotationMarkdownReport, getAutoTagsForEvent } from '@/ui/playtest/PlaytestAnnotationAssistant.helpers';
import type { AnnotationAssistantConfig } from '@/ui/playtest/config/annotationConfig';
import type { PlaytestEvent, PlaytestSession } from '@/ui/playtest/systems/playtestLogger';
import type { PlaytestLogger } from '@/ui/playtest/systems/playtestLogger';

vi.mock('@/ui/playtest/systems/playtestLogger', async (importOriginal) => {
  const actual = await importOriginal();
  return {
    ...actual,
    getPlaytestLogger: vi.fn(() => mockLogger),
  };
});

const baseEvent: PlaytestEvent = {
  id: 'evt-1',
  timestamp: 1_700_000_000_000,
  type: 'tap',
  sessionId: 'session-1',
  userId: 'player-1',
};

const baseSession: PlaytestSession = {
  id: 'session-1',
  startTime: 1_700_000_000_000,
  deviceInfo: {
    userAgent: 'jest',
    platform: 'ios',
    vendor: 'apple',
    screenResolution: '100x100',
    colorDepth: 24,
    pixelRatio: 2,
    touchSupport: true,
    maxTouchPoints: 5,
  },
  events: [baseEvent],
  buildVersion: '1.0.0',
  platform: 'ios',
  completed: true,
  crashDetected: false,
  errorCount: 0,
  interactionCount: 1,
};

const mockLogger: PlaytestLogger = {
  getRecentEvents: vi.fn(() => [baseEvent]),
  getCurrentSession: vi.fn(() => baseSession),
} as unknown as PlaytestLogger;

const testConfig: AnnotationAssistantConfig = {
  tags: [
    { id: 'ftue', label: 'FTUE', color: '#38bdf8' },
    { id: 'input', label: 'Input lag', color: '#fbbf24' },
  ],
  quickNotes: [
    { id: 'confusion', label: 'Confusion Spike', template: 'Player confused', tags: ['ftue'] },
  ],
  severities: {
    info: { label: 'Info', color: '#38bdf8', accent: 'rgba(56,189,248,.15)' },
    issue: { label: 'Issue', color: '#fbbf24', accent: 'rgba(251,191,36,.18)' },
    blocker: { label: 'Blocker', color: '#f87171', accent: 'rgba(248,113,113,.2)' },
  },
  timeline: {
    refreshIntervalMs: 5_000,
    maxVisibleEvents: 5,
    markerSizePx: 8,
    showEventTypeLegend: false,
  },
  markdown: {
    headingLevel: 3,
    includeSummary: true,
    includeTimeline: true,
    includeDeviceInfo: true,
    includePerformance: true,
    footnote: 'Generated by tests',
  },
  eventTaggingRules: {
    tap: ['input'],
  },
};

describe('helper utilities', () => {
  it('getAutoTagsForEvent returns configured tags', () => {
    expect(getAutoTagsForEvent(baseEvent, testConfig)).toEqual(['input']);
  });

  it('buildAnnotationMarkdownReport includes annotations, device info, and footnote', () => {
    const annotations: PlaytestAnnotation[] = [
      {
        id: 'annotation_1',
        title: 'Input delay',
        body: 'Player noticed 250ms lag',
        severity: 'issue',
        tags: ['input'],
        timestamp: baseEvent.timestamp + 1000,
        eventId: baseEvent.id,
      },
    ];

    const markdown = buildAnnotationMarkdownReport({
      annotations,
      session: baseSession,
      events: [baseEvent],
      config: testConfig,
    });

    expect(markdown).toContain('### [ISSUE] Input delay');
    expect(markdown).toContain('Device Info');
    expect(markdown).toContain('## Timeline Extract');
    expect(markdown).toContain('Generated by tests');
  });
});

describe('PlaytestAnnotationAssistant component', () => {
  beforeEach(() => {
    vi.useFakeTimers();
    (mockLogger.getRecentEvents as unknown as ReturnType<typeof vi.fn>).mockReturnValue([baseEvent]);
    (mockLogger.getCurrentSession as unknown as ReturnType<typeof vi.fn>).mockReturnValue(baseSession);
  });

  afterEach(() => {
    vi.clearAllMocks();
    vi.useRealTimers();
  });

  it('creates annotation through quick note and calls callbacks', () => {
    const handleAnnotationCreate = vi.fn();
    const handleExport = vi.fn();

    render(
      <PlaytestAnnotationAssistant
        logger={mockLogger}
        config={testConfig}
        onAnnotationCreate={handleAnnotationCreate}
        onExport={handleExport}
      />,
    );

    const quickNoteButton = screen.getByRole('button', { name: /Confusion Spike/i });
    fireEvent.click(quickNoteButton);

    const saveButton = screen.getByRole('button', { name: /Save Annotation/i });
    fireEvent.click(saveButton);

    expect(handleAnnotationCreate).toHaveBeenCalledTimes(1);
    const createdAnnotation = handleAnnotationCreate.mock.calls[0][0] as PlaytestAnnotation;
    expect(createdAnnotation.quickNoteId).toBe('confusion');
    expect(createdAnnotation.tags).toContain('ftue');

    const annotationsHeader = screen.getByRole('heading', { name: /Annotations/i });
    const annotationList = annotationsHeader.closest('.paa-card')?.querySelector('ul');
    expect(annotationList).toBeTruthy();
    expect(within(annotationList as HTMLElement).getByText(/Confusion Spike/)).toBeInTheDocument();

    const exportButton = screen.getByRole('button', { name: /Export Markdown/i });
    fireEvent.click(exportButton);
    expect(handleExport).toHaveBeenCalledTimes(1);
  });
});
