/**
 * Assignment Undo/Redo Configuration - NP-020
 * 
 * Configuration schema for the Idle Village Resident Assignment Undo UX.
 * Defines undo/redo timeline, shortcuts, diff summary, and PersistenceService
 * integration settings for resident assignment management.
 * 
 * @since 2026-01-13
 * @author Cascade
 */

/**
 * Assignment change types for undo/redo tracking
 */
export enum AssignmentChangeType {
  RESIDENT_ASSIGNED = 'resident_assigned',
  RESIDENT_UNASSIGNED = 'resident_unassigned',
  RESIDENT_MOVED = 'resident_moved',
  ACTIVITY_CHANGED = 'activity_changed',
  BATCH_ASSIGNMENT = 'batch_assignment',
  BATCH_UNASSIGNMENT = 'batch_unassignment',
  EMERGENCY_REASSIGNMENT = 'emergency_reassignment',
  AUTO_ASSIGNMENT = 'auto_assignment',
}

/**
 * Keyboard shortcut configuration
 */
export interface KeyboardShortcutConfig {
  /** Key combination (e.g., 'Ctrl+Z', 'Cmd+Z') */
  key: string;
  /** Action to perform */
  action: 'undo' | 'redo' | 'clear_history' | 'toggle_timeline';
  /** Whether shortcut is enabled */
  enabled: boolean;
  /** Description for UI display */
  description: string;
  /** Platform-specific variants */
  platformVariants?: {
    mac?: string;
    windows?: string;
    linux?: string;
  };
}

/**
 * Assignment change entry for timeline
 */
export interface AssignmentChange {
  /** Unique identifier for the change */
  id: string;
  /** Type of change */
  type: AssignmentChangeType;
  /** Timestamp when change occurred */
  timestamp: number;
  /** Description of the change */
  description: string;
  /** Previous state (before change) */
  previousState: AssignmentState;
  /** New state (after change) */
  newState: AssignmentState;
  /** User who made the change */
  userId?: string;
  /** Session identifier */
  sessionId: string;
  /** Whether change was automatically generated */
  autoGenerated: boolean;
  /** Additional metadata */
  metadata: {
    affectedResidents: string[];
    affectedActivities: string[];
    reason?: string;
    priority?: number;
    context?: Record<string, unknown>;
  };
}

/**
 * Assignment state snapshot
 */
export interface AssignmentState {
  /** Resident assignments */
  assignments: Record<string, string>; // residentId -> activityId
  /** Activity capacities */
  activityCapacities: Record<string, number>;
  /** Resident availability */
  residentAvailability: Record<string, boolean>;
  /** Activity requirements */
  activityRequirements: Record<string, string[]>; // activityId -> requiredSpecializations
  /** Timestamp of snapshot */
  timestamp: number;
  /** Checksum for integrity verification */
  checksum: string;
}

/**
 * Diff summary for assignment changes
 */
export interface AssignmentDiffSummary {
  /** Change ID */
  changeId: string;
  /** Type of change */
  type: AssignmentChangeType;
  /** Brief description */
  summary: string;
  /** Detailed changes */
  details: {
    /** Residents added to activities */
    added: Array<{
      residentId: string;
      residentName: string;
      activityId: string;
      activityName: string;
    }>;
    /** Residents removed from activities */
    removed: Array<{
      residentId: string;
      residentName: string;
      activityId: string;
      activityName: string;
    }>;
    /** Residents moved between activities */
    moved: Array<{
      residentId: string;
      residentName: string;
      fromActivityId: string;
      fromActivityName: string;
      toActivityId: string;
      toActivityName: string;
    }>;
  };
  /** Impact metrics */
  impact: {
    /** Number of affected residents */
    affectedResidents: number;
    /** Number of affected activities */
    affectedActivities: number;
    /** Priority level of change */
    priority: 'low' | 'medium' | 'high' | 'critical';
    /** Estimated impact on productivity */
    productivityImpact: number; // -1 to 1 scale
  };
  /** Timestamp */
  timestamp: number;
}

/**
 * Timeline entry for visual representation
 */
export interface TimelineEntry {
  /** Change ID */
  id: string;
  /** Position in timeline (0-1) */
  position: number;
  /** Type of change */
  type: AssignmentChangeType;
  /** Brief description */
  label: string;
  /** Timestamp */
  timestamp: number;
  /** Whether entry is current state */
  isCurrent: boolean;
  /** Whether entry can be navigated to */
  navigable: boolean;
  /** Visual properties */
  visual: {
    color: string;
    icon: string;
    size: 'small' | 'medium' | 'large';
    opacity: number;
  };
}

/**
 * Persistence configuration for undo/redo data
 */
export interface AssignmentUndoPersistenceConfig {
  /** Whether persistence is enabled */
  enabled: boolean;
  /** Storage key prefix */
  storageKey: string;
  /** Maximum number of changes to persist */
  maxPersistedChanges: number;
  /** Auto-save interval in milliseconds */
  autoSaveInterval: number;
  /** Whether to compress persisted data */
  compressionEnabled: boolean;
  /** Data retention period in hours */
  retentionHours: number;
  /** Whether to encrypt persisted data */
  encryptionEnabled: boolean;
  /** Backup configuration */
  backup: {
    enabled: boolean;
    interval: number; // milliseconds
    maxBackups: number;
    location: 'local' | 'cloud' | 'both';
  };
}

/**
 * UI configuration for undo/redo components
 */
export interface AssignmentUndoUIConfig {
  /** Timeline configuration */
  timeline: {
    /** Whether timeline is visible */
    visible: boolean;
    /** Maximum number of entries to display */
    maxEntries: number;
    /** Timeline orientation */
    orientation: 'horizontal' | 'vertical';
    /** Whether to show timestamps */
    showTimestamps: boolean;
    /** Whether to show change descriptions */
    showDescriptions: boolean;
    /** Animation settings */
    animations: {
      enabled: boolean;
      duration: number; // milliseconds
      easing: string;
    };
  };
  /** Diff summary configuration */
  diffSummary: {
    /** Whether diff summary is visible */
    visible: boolean;
    /** Maximum number of changes to show */
    maxChanges: number;
    /** Whether to group similar changes */
    groupSimilarChanges: boolean;
    /** Whether to show impact metrics */
    showImpactMetrics: boolean;
    /** Detail level */
    detailLevel: 'brief' | 'detailed' | 'comprehensive';
  };
  /** Keyboard shortcuts configuration */
  shortcuts: {
    /** Whether shortcuts are enabled */
    enabled: boolean;
    /** Whether to show shortcut hints */
    showHints: boolean;
    /** Shortcut delay in milliseconds */
    delay: number;
    /** Whether to prevent browser defaults */
    preventDefaults: boolean;
  };
  /** Visual styling */
  visual: {
    /** Theme colors */
    colors: {
      primary: string;
      secondary: string;
      accent: string;
      success: string;
      warning: string;
      danger: string;
      background: string;
      foreground: string;
      border: string;
      shadow: string;
    };
    /** Change type colors */
    changeTypeColors: {
      [AssignmentChangeType.RESIDENT_ASSIGNED]: string;
      [AssignmentChangeType.RESIDENT_UNASSIGNED]: string;
      [AssignmentChangeType.RESIDENT_MOVED]: string;
      [AssignmentChangeType.ACTIVITY_CHANGED]: string;
      [AssignmentChangeType.BATCH_ASSIGNMENT]: string;
      [AssignmentChangeType.BATCH_UNASSIGNMENT]: string;
      [AssignmentChangeType.EMERGENCY_REASSIGNMENT]: string;
      [AssignmentChangeType.AUTO_ASSIGNMENT]: string;
    };
    /** Typography */
    typography: {
      fontFamily: string;
      fontSize: {
        small: string;
        medium: string;
        large: string;
      };
      fontWeight: {
        normal: number;
        bold: number;
      };
    };
    /** Border radius */
    borderRadius: {
      small: string;
      medium: string;
      large: string;
    };
  };
}

/**
 * Performance configuration
 */
export interface AssignmentUndoPerformanceConfig {
  /** Maximum number of changes to keep in memory */
  maxInMemoryChanges: number;
  /** Debounce time for change detection (milliseconds) */
  changeDebounceMs: number;
  /** Whether to enable virtual scrolling for timeline */
  enableVirtualScrolling: boolean;
  /** Cache configuration */
  cache: {
    enabled: boolean;
    ttl: number; // milliseconds
    maxSize: number;
  };
  /** Lazy loading settings */
  lazyLoading: {
    enabled: boolean;
    threshold: number; // pixels from viewport
    batchSize: number;
  };
  /** Memory monitoring */
  memoryMonitoring: {
    enabled: boolean;
    threshold: number; // MB
    cleanupThreshold: number; // percentage
  };
}

/**
 * Complete assignment undo/redo configuration
 */
export interface AssignmentUndoConfig {
  /** UI configuration */
  ui: AssignmentUndoUIConfig;
  /** Persistence configuration */
  persistence: AssignmentUndoPersistenceConfig;
  /** Performance configuration */
  performance: AssignmentUndoPerformanceConfig;
  /** Keyboard shortcuts */
  keyboardShortcuts: KeyboardShortcutConfig[];
  /** Maximum history depth */
  maxHistoryDepth: number;
  /** Whether to enable automatic change detection */
  autoDetectChanges: boolean;
  /** Change detection interval (milliseconds) */
  changeDetectionInterval: number;
  /** Whether to enable collaborative features */
  collaborativeFeatures: {
    enabled: boolean;
    syncInterval: number; // milliseconds
    conflictResolution: 'latest' | 'merge' | 'prompt';
  };
}

/**
 * Default keyboard shortcuts
 */
export const DEFAULT_KEYBOARD_SHORTCUTS: KeyboardShortcutConfig[] = [
  {
    key: 'Ctrl+Z',
    action: 'undo',
    enabled: true,
    description: 'Undo last assignment change',
    platformVariants: {
      mac: 'Cmd+Z',
      windows: 'Ctrl+Z',
      linux: 'Ctrl+Z',
    },
  },
  {
    key: 'Ctrl+Y',
    action: 'redo',
    enabled: true,
    description: 'Redo last undone change',
    platformVariants: {
      mac: 'Cmd+Shift+Z',
      windows: 'Ctrl+Y',
      linux: 'Ctrl+Y',
    },
  },
  {
    key: 'Ctrl+Shift+Z',
    action: 'redo',
    enabled: true,
    description: 'Redo last undone change (alternative)',
    platformVariants: {
      mac: 'Cmd+Shift+Z',
      windows: 'Ctrl+Shift+Z',
      linux: 'Ctrl+Shift+Z',
    },
  },
  {
    key: 'Ctrl+H',
    action: 'toggle_timeline',
    enabled: true,
    description: 'Toggle assignment timeline visibility',
    platformVariants: {
      mac: 'Cmd+H',
      windows: 'Ctrl+H',
      linux: 'Ctrl+H',
    },
  },
  {
    key: 'Ctrl+Shift+H',
    action: 'clear_history',
    enabled: true,
    description: 'Clear assignment history',
    platformVariants: {
      mac: 'Cmd+Shift+H',
      windows: 'Ctrl+Shift+H',
      linux: 'Ctrl+Shift+H',
    },
  },
];

/**
 * Default assignment undo configuration
 */
export const DEFAULT_ASSIGNMENT_UNDO_CONFIG: AssignmentUndoConfig = {
  ui: {
    timeline: {
      visible: true,
      maxEntries: 50,
      orientation: 'horizontal',
      showTimestamps: true,
      showDescriptions: true,
      animations: {
        enabled: true,
        duration: 300,
        easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
    diffSummary: {
      visible: true,
      maxChanges: 10,
      groupSimilarChanges: true,
      showImpactMetrics: true,
      detailLevel: 'detailed',
    },
    shortcuts: {
      enabled: true,
      showHints: true,
      delay: 100,
      preventDefaults: true,
    },
    visual: {
      colors: {
        primary: 'rgb(59, 130, 246)', // blue-500
        secondary: 'rgb(107, 114, 128)', // gray-500
        accent: 'rgb(168, 85, 247)', // purple-500
        success: 'rgb(34, 197, 94)', // green-500
        warning: 'rgb(251, 191, 36)', // amber-400
        danger: 'rgb(239, 68, 68)', // red-500
        background: 'rgb(30, 41, 59)', // slate-800
        foreground: 'rgb(248, 250, 252)', // slate-50
        border: 'rgb(71, 85, 105)', // slate-600
        shadow: 'rgba(0, 0, 0, 0.3)',
      },
      changeTypeColors: {
        [AssignmentChangeType.RESIDENT_ASSIGNED]: 'rgb(34, 197, 94)', // green-500
        [AssignmentChangeType.RESIDENT_UNASSIGNED]: 'rgb(239, 68, 68)', // red-500
        [AssignmentChangeType.RESIDENT_MOVED]: 'rgb(59, 130, 246)', // blue-500
        [AssignmentChangeType.ACTIVITY_CHANGED]: 'rgb(168, 85, 247)', // purple-500
        [AssignmentChangeType.BATCH_ASSIGNMENT]: 'rgb(34, 197, 94)', // green-500
        [AssignmentChangeType.BATCH_UNASSIGNMENT]: 'rgb(239, 68, 68)', // red-500
        [AssignmentChangeType.EMERGENCY_REASSIGNMENT]: 'rgb(251, 191, 36)', // amber-400
        [AssignmentChangeType.AUTO_ASSIGNMENT]: 'rgb(107, 114, 128)', // gray-500
      },
      typography: {
        fontFamily: 'ui-monospace, SFMono-Regular, "SF Mono", Consolas, "Liberation Mono", Menlo, monospace',
        fontSize: {
          small: '0.75rem',
          medium: '0.875rem',
          large: '1rem',
        },
        fontWeight: {
          normal: 400,
          bold: 600,
        },
      },
      borderRadius: {
        small: '0.25rem',
        medium: '0.5rem',
        large: '0.75rem',
      },
    },
  },
  persistence: {
    enabled: true,
    storageKey: 'idle-village-assignment-undo',
    maxPersistedChanges: 100,
    autoSaveInterval: 5000, // 5 seconds
    compressionEnabled: true,
    retentionHours: 24,
    encryptionEnabled: false,
    backup: {
      enabled: true,
      interval: 60000, // 1 minute
      maxBackups: 5,
      location: 'local',
    },
  },
  performance: {
    maxInMemoryChanges: 200,
    changeDebounceMs: 300,
    enableVirtualScrolling: true,
    cache: {
      enabled: true,
      ttl: 300000, // 5 minutes
      maxSize: 50,
    },
    lazyLoading: {
      enabled: true,
      threshold: 200,
      batchSize: 10,
    },
    memoryMonitoring: {
      enabled: true,
      threshold: 50, // 50MB
      cleanupThreshold: 80, // 80%
    },
  },
  keyboardShortcuts: DEFAULT_KEYBOARD_SHORTCUTS,
  maxHistoryDepth: 100,
  autoDetectChanges: true,
  changeDetectionInterval: 1000, // 1 second
  collaborativeFeatures: {
    enabled: false,
    syncInterval: 5000, // 5 seconds
    conflictResolution: 'latest',
  },
};

/**
 * Utility functions for assignment undo configuration
 */

/**
 * Generate unique change ID
 */
export function generateChangeId(): string {
  return `change-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

/**
 * Generate checksum for assignment state
 */
export function generateStateChecksum(state: AssignmentState): string {
  const data = JSON.stringify(state);
  let hash = 0;
  for (let i = 0; i < data.length; i++) {
    const char = data.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash; // Convert to 32-bit integer
  }
  return hash.toString(36);
}

/**
 * Get keyboard shortcut for current platform
 */
export function getPlatformShortcut(shortcut: KeyboardShortcutConfig): string {
  const platform = navigator.platform.toLowerCase();
  
  if (platform.includes('mac') && shortcut.platformVariants?.mac) {
    return shortcut.platformVariants.mac;
  }
  if (platform.includes('win') && shortcut.platformVariants?.windows) {
    return shortcut.platformVariants.windows;
  }
  if (platform.includes('linux') && shortcut.platformVariants?.linux) {
    return shortcut.platformVariants.linux;
  }
  
  return shortcut.key;
}

/**
 * Format timestamp for display
 */
export function formatTimestamp(timestamp: number): string {
  const date = new Date(timestamp);
  return date.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });
}

/**
 * Calculate change priority based on impact
 */
export function calculateChangePriority(impact: AssignmentDiffSummary['impact']): 'low' | 'medium' | 'high' | 'critical' {
  if (impact.affectedResidents >= 10 || impact.productivityImpact >= 0.7) {
    return 'critical';
  }
  if (impact.affectedResidents >= 5 || impact.productivityImpact >= 0.4) {
    return 'high';
  }
  if (impact.affectedResidents >= 2 || impact.productivityImpact >= 0.2) {
    return 'medium';
  }
  return 'low';
}

/**
 * Get color for change type
 */
export function getChangeTypeColor(type: AssignmentChangeType, config: AssignmentUndoConfig): string {
  return config.ui.visual.changeTypeColors[type];
}

/**
 * Get icon for change type
 */
export function getChangeTypeIcon(type: AssignmentChangeType): string {
  switch (type) {
    case AssignmentChangeType.RESIDENT_ASSIGNED:
      return '➕';
    case AssignmentChangeType.RESIDENT_UNASSIGNED:
      return '➖';
    case AssignmentChangeType.RESIDENT_MOVED:
      return '↔️';
    case AssignmentChangeType.ACTIVITY_CHANGED:
      return '🔄';
    case AssignmentChangeType.BATCH_ASSIGNMENT:
      return '📋';
    case AssignmentChangeType.BATCH_UNASSIGNMENT:
      return '🗑️';
    case AssignmentChangeType.EMERGENCY_REASSIGNMENT:
      return '🚨';
    case AssignmentChangeType.AUTO_ASSIGNMENT:
      return '🤖';
    default:
      return '📝';
  }
}
