// Generated by scripts/scatter-clouds.mjs — do not edit by hand.
import type { CloudBand } from './atmosphereAssets';

export const cloudBands: CloudBand[] = [{
  "name": "far",
  "driftSeconds": 2000,
  "opacity": 1,
  "shadowOpacity": 0,
  "scale": 1,
  "sprites": [
    {
      "src": "clouds/cloud_06.webp",
      "width": 395,
      "y": 1414,
      "delaySeconds": 132,
      "shadowSrc": "cloud-shadows/cloud_06_shadow.webp"
    },
    {
      "src": "clouds/cloud_01.webp",
      "width": 412,
      "y": 911,
      "delaySeconds": 1438,
      "shadowSrc": "cloud-shadows/cloud_01_shadow.webp"
    },
    {
      "src": "clouds/cloud_04.webp",
      "width": 273,
      "y": 1051,
      "delaySeconds": 1153,
      "shadowSrc": "cloud-shadows/cloud_04_shadow.webp"
    },
    {
      "src": "clouds/cloud_05.webp",
      "width": 401,
      "y": 272,
      "delaySeconds": 360,
      "shadowSrc": "cloud-shadows/cloud_05_shadow.webp"
    },
    {
      "src": "clouds/cloud_03.webp",
      "width": 383,
      "y": 2452,
      "delaySeconds": 926,
      "shadowSrc": "cloud-shadows/cloud_03_shadow.webp"
    },
    {
      "src": "clouds/cloud_02.webp",
      "width": 379,
      "y": 1808,
      "delaySeconds": 1111,
      "shadowSrc": "cloud-shadows/cloud_02_shadow.webp"
    },
    {
      "src": "clouds/cloud_06.webp",
      "width": 422,
      "y": 1888,
      "delaySeconds": 1101,
      "shadowSrc": "cloud-shadows/cloud_06_shadow.webp"
    },
    {
      "src": "clouds/cloud_01.webp",
      "width": 247,
      "y": 1816,
      "delaySeconds": 857,
      "shadowSrc": "cloud-shadows/cloud_01_shadow.webp"
    },
    {
      "src": "clouds/cloud_04.webp",
      "width": 336,
      "y": 363,
      "delaySeconds": 1305,
      "shadowSrc": "cloud-shadows/cloud_04_shadow.webp"
    }
  ]
}];
