// Generated by scripts/scatter-clouds.mjs — do not edit by hand.
import type { CloudBand } from './atmosphereAssets';

export const cloudBands: CloudBand[] = [
  {
    "name": "far",
    "driftSeconds": 2120,
    "opacity": 0.85,
    "shadowOpacity": 0.02,
    "scale": 0.78,
    "sprites": [
      {
        "src": "clouds/cloud_02.webp",
        "width": 361,
        "y": 1414,
        "delaySeconds": 1279,
        "shadowSrc": "cloud-shadows/cloud_02_shadow.webp"
      },
      {
        "src": "clouds/cloud_05.webp",
        "width": 244,
        "y": 2013,
        "delaySeconds": 1808,
        "shadowSrc": "cloud-shadows/cloud_05_shadow.webp"
      },
      {
        "src": "clouds/cloud_04.webp",
        "width": 208,
        "y": 630,
        "delaySeconds": 147,
        "shadowSrc": "cloud-shadows/cloud_04_shadow.webp"
      },
      {
        "src": "clouds/cloud_06.webp",
        "width": 405,
        "y": 1588,
        "delaySeconds": 179,
        "shadowSrc": "cloud-shadows/cloud_06_shadow.webp"
      },
      {
        "src": "clouds/cloud_03.webp",
        "width": 356,
        "y": 2052,
        "delaySeconds": 1853,
        "shadowSrc": "cloud-shadows/cloud_03_shadow.webp"
      },
      {
        "src": "clouds/cloud_01.webp",
        "width": 392,
        "y": 1021,
        "delaySeconds": 1702,
        "shadowSrc": "cloud-shadows/cloud_01_shadow.webp"
      },
      {
        "src": "clouds/cloud_02.webp",
        "width": 275,
        "y": 696,
        "delaySeconds": 751,
        "shadowSrc": "cloud-shadows/cloud_02_shadow.webp"
      },
      {
        "src": "clouds/cloud_05.webp",
        "width": 447,
        "y": 2707,
        "delaySeconds": 1256,
        "shadowSrc": "cloud-shadows/cloud_05_shadow.webp"
      }
    ]
  },
  {
    "name": "mid",
    "driftSeconds": 1210,
    "opacity": 0.92,
    "shadowOpacity": 0.03,
    "scale": 1,
    "sprites": [
      {
        "src": "clouds/cloud_05.webp",
        "width": 238,
        "y": 1414,
        "delaySeconds": 706,
        "shadowSrc": "cloud-shadows/cloud_05_shadow.webp"
      },
      {
        "src": "clouds/cloud_06.webp",
        "width": 247,
        "y": 1158,
        "delaySeconds": 1148,
        "shadowSrc": "cloud-shadows/cloud_06_shadow.webp"
      },
      {
        "src": "clouds/cloud_03.webp",
        "width": 419,
        "y": 931,
        "delaySeconds": 1151,
        "shadowSrc": "cloud-shadows/cloud_03_shadow.webp"
      },
      {
        "src": "clouds/cloud_04.webp",
        "width": 411,
        "y": 2602,
        "delaySeconds": 777,
        "shadowSrc": "cloud-shadows/cloud_04_shadow.webp"
      },
      {
        "src": "clouds/cloud_01.webp",
        "width": 237,
        "y": 571,
        "delaySeconds": 462,
        "shadowSrc": "cloud-shadows/cloud_01_shadow.webp"
      }
    ]
  },
  {
    "name": "near",
    "driftSeconds": 710,
    "opacity": 1,
    "shadowOpacity": 0.04,
    "scale": 1.35,
    "sprites": [
      {
        "src": "clouds/cloud_01.webp",
        "width": 321,
        "y": 1414,
        "delaySeconds": 511,
        "shadowSrc": "cloud-shadows/cloud_01_shadow.webp"
      },
      {
        "src": "clouds/cloud_06.webp",
        "width": 249,
        "y": 2154,
        "delaySeconds": 190,
        "shadowSrc": "cloud-shadows/cloud_06_shadow.webp"
      },
      {
        "src": "clouds/cloud_05.webp",
        "width": 380,
        "y": 2067,
        "delaySeconds": 665,
        "shadowSrc": "cloud-shadows/cloud_05_shadow.webp"
      }
    ]
  }
];
