/**
 * Asset Mapping Configuration for Physics Lab
 * 
 * Maps asset IDs to file paths for audio and shader textures.
 * Generated by the asset downloader CLI - DO NOT EDIT MANUALLY.
 * 
 * @author Cascade
 * @since 2026-02-19
 */

import { z } from 'zod';

/**
 * Schema for individual asset metadata
 */
const AssetMetadataSchema = z.object({
  /** Source repository (freesound.org, opengameart.org, placeholder) */
  source: z.string(),
  /** License type (CC0, CC-BY, etc.) */
  license: z.string(),
  /** File size in bytes */
  size: z.number(),
  /** SHA256 checksum for integrity validation */
  checksum: z.string(),
});

/**
 * Schema for the complete asset mapping configuration
 */
export const AssetMappingSchema = z.object({
  /** Audio asset mappings (UI sounds) */
  audio: z.record(z.string(), z.string()),
  /** Shader texture mappings (visual effects) */
  shaders: z.record(z.string(), z.string()),
  /** Metadata about all assets */
  metadata: z.object({
    /** Last update timestamp */
    lastUpdated: z.string(),
    /** Total number of assets */
    totalAssets: z.number(),
    /** Detailed information for each asset */
    sourceInfo: z.record(z.string(), AssetMetadataSchema),
  }),
});

/**
 * Type inference from the schema
 */
export type AssetMapping = z.infer<typeof AssetMappingSchema>;
export type AssetMetadata = z.infer<typeof AssetMetadataSchema>;

/**
 * Default asset mapping configuration
 * This will be overwritten by the asset downloader CLI
 */
export const DEFAULT_ASSET_MAPPING: AssetMapping = {
  audio: {
    'ui-thud': '/audio/physics-lab/ui-thud.wav',
    'ui-shimmer': '/audio/physics-lab/ui-shimmer.wav',
    'slot-snap': '/audio/physics-lab/slot-snap.wav',
    'power-up': '/audio/physics-lab/power-up.wav',
  },
  shaders: {
    'liquid-gauge': '/assets/shaders/physics-lab/liquid-gauge.png',
    'fog-slot': '/assets/shaders/physics-lab/fog-slot.png',
    'foil-card': '/assets/shaders/physics-lab/foil-card.png',
    'particle-sprite': '/assets/shaders/physics-lab/particle-sprite.png',
  },
  metadata: {
    lastUpdated: new Date().toISOString(),
    totalAssets: 8,
    sourceInfo: {
      'ui-thud': {
        source: 'placeholder',
        license: 'CC0',
        size: 0,
        checksum: 'placeholder',
      },
      'ui-shimmer': {
        source: 'placeholder',
        license: 'CC0',
        size: 0,
        checksum: 'placeholder',
      },
      'slot-snap': {
        source: 'placeholder',
        license: 'CC0',
        size: 0,
        checksum: 'placeholder',
      },
      'power-up': {
        source: 'placeholder',
        license: 'CC0',
        size: 0,
        checksum: 'placeholder',
      },
      'liquid-gauge': {
        source: 'placeholder',
        license: 'CC0',
        size: 0,
        checksum: 'placeholder',
      },
      'fog-slot': {
        source: 'placeholder',
        license: 'CC0',
        size: 0,
        checksum: 'placeholder',
      },
      'foil-card': {
        source: 'placeholder',
        license: 'CC0',
        size: 0,
        checksum: 'placeholder',
      },
      'particle-sprite': {
        source: 'placeholder',
        license: 'CC0',
        size: 0,
        checksum: 'placeholder',
      },
    },
  },
};

/**
 * Helper function to get asset URL by type and ID
 */
export function getAssetUrl(mapping: AssetMapping, type: 'audio' | 'shaders', assetId: string): string | null {
  return mapping[type][assetId] || null;
}

/**
 * Helper function to get asset metadata
 */
export function getAssetMetadata(mapping: AssetMapping, assetId: string): AssetMetadata | null {
  return mapping.metadata.sourceInfo[assetId] || null;
}

/**
 * Helper function to check if asset exists
 */
export function hasAsset(mapping: AssetMapping, type: 'audio' | 'shaders', assetId: string): boolean {
  return assetId in mapping[type];
}

/**
 * Helper function to get all asset IDs by type
 */
export function getAssetIds(mapping: AssetMapping, type: 'audio' | 'shaders'): string[] {
  return Object.keys(mapping[type]);
}

/**
 * Helper function to validate asset mapping integrity
 */
export function validateAssetMapping(mapping: AssetMapping): boolean {
  try {
    AssetMappingSchema.parse(mapping);
    return true;
  } catch {
    return false;
  }
}

// Export the default as the current mapping (will be updated by CLI)
export const ASSET_MAPPING = DEFAULT_ASSET_MAPPING;
