declare global {
  interface Window {
    __ENABLE_IDLE_VILLAGE_TEST_HOOKS?: boolean;
    __ENABLE_IDLE_VILLAGE_DIAGNOSTICS?: boolean;
  }
}

export type DiagnosticsChannelId =
  | 'picker'
  | 'validators'
  | 'risk'
  | 'theater'
  | 'drag'
  | (string & {});

export type PickerDiagnosticsPayload = {
  slotId?: string | null;
  residentId?: string | null;
  action?: string;
  details?: Record<string, unknown>;
  [key: string]: unknown;
};

export type ValidatorDiagnosticsPayload = {
  slotId?: string;
  residentId?: string | null;
  validation?: Record<string, unknown>;
  dropState?: Record<string, unknown>;
  [key: string]: unknown;
};

export type RiskDiagnosticsPayload = {
  activityId?: string;
  injuryPct?: number;
  deathPct?: number;
  warnings?: string[];
  [key: string]: unknown;
};

export type TheaterDiagnosticsPayload = {
  primarySlotId?: string | null;
  resolvedPrimarySlotId?: string | null;
  previewIds?: string[];
  action?: string;
  [key: string]: unknown;
};

/**
 * Diagnostic log entry for the unified bundle.
 */
export interface DiagnosticLog<TPayload = unknown> {
  /** Logical channel (picker, validators, risk, etc.). */
  channel: DiagnosticsChannelId;
  /** UNIX timestamp (ms) for chronological sort. */
  timestamp: number;
  /** Severity level. */
  level: 'log' | 'info' | 'warn' | 'debug' | 'error';
  /** Logical scope/component name. */
  scope: string;
  /** Human-friendly message. */
  message: string;
  /** Optional payload for structured context. */
  payload?: TPayload;
  /** Optional tags for filtering (e.g., ['drag', 'quest']). */
  tags?: string[];
}

/**
 * Descriptor for a diagnostics channel exposed to the panel.
 */
interface ChannelDefinition<TPayload = unknown> {
  /** Unique identifier (matches DiagnosticLog.channel). */
  id: DiagnosticsChannelId;
  /** UI label. */
  label: string;
  /** Description for tooltips/docs. */
  description: string;
  /** Optional per-channel buffer size (default 400). */
  bufferSize?: number;
  /** Optional formatter run before persisting a log entry. */
  formatter?: (entry: DiagnosticLog<TPayload>) => DiagnosticLog;
}

export type ChannelRegistry = Record<DiagnosticsChannelId, ChannelDefinition>;

/**
 * Filter options for extracting diagnostic logs.
 */
export interface DiagnosticsFilter {
  /** Channel to filter by (omit = all). */
  channel?: DiagnosticsChannelId;
  /** Only include logs newer than this timestamp. */
  since?: number;
  /** Require at least one matching tag. */
  tags?: string[];
}

const defaultChannels: ChannelRegistry = {
  picker: {
    id: 'picker',
    label: 'Worker Picker',
    description: 'Logs generated by worker picker interactions and replays.',
    bufferSize: 400,
  },
  validators: {
    id: 'validators',
    label: 'Location Validators',
    description: 'Validation hints, warnings and drop blocking reasons.',
    bufferSize: 400,
  },
  risk: {
    id: 'risk',
    label: 'Quest Risk Stripes',
    description: 'Risk percentage snapshots and mismatches.',
    bufferSize: 400,
  },
  theater: {
    id: 'theater',
    label: 'Theater Overlay',
    description: 'Hover timers, preview selections, and overlay interactions.',
    bufferSize: 400,
  },
  drag: {
    id: 'drag',
    label: 'Drag Preview',
    description: 'Drag preview instrumentation and overlay diagnostics.',
    bufferSize: 200,
  },
};

/**
 * Global store for diagnostic logs, accessible by the diagnostics panel.
 */
const diagnosticLogs: DiagnosticLog[] = [];
const perChannelLogs: Partial<Record<string, DiagnosticLog[]>> = {};
const listeners = new Set<() => void>();
let registeredChannels: ChannelRegistry = { ...defaultChannels };

const notifyListeners = () => {
  listeners.forEach((listener) => {
    try {
      listener();
    } catch (error) {
      console.warn('[IdleVillageDiagnostics] listener error', error);
    }
  });
};

export const configureDiagnosticsChannels = (registry: ChannelRegistry): void => {
  registeredChannels = { ...registry };
  const registeredIds = Object.keys(registeredChannels);
  registeredIds.forEach((id) => {
    if (!perChannelLogs[id]) {
      perChannelLogs[id] = [];
    }
  });
};

// Ensure default channels have buffers
configureDiagnosticsChannels(defaultChannels);

export const getDiagnosticsChannelRegistry = (): ChannelRegistry => registeredChannels;

export const subscribeToDiagnostics = (listener: () => void): (() => void) => {
  listeners.add(listener);
  return () => {
    listeners.delete(listener);
  };
};

/**
 * Adds a log entry to the global store if diagnostics are enabled.
 */
const recordLog = (log: DiagnosticLog): void => {
  if (!isDiagnosticsEnabled()) {
    return;
  }

  const channelDef =
    registeredChannels[log.channel] ??
    (registeredChannels[log.channel] = {
      id: log.channel,
      label: log.channel,
      description: `Diagnostics channel ${log.channel}`,
      bufferSize: 400,
    });
  const normalizedLog = channelDef?.formatter ? channelDef.formatter(log) : log;

  diagnosticLogs.push(normalizedLog);
  if (diagnosticLogs.length > 1000) {
    diagnosticLogs.splice(0, diagnosticLogs.length - 1000);
  }

  const channelBuffer = perChannelLogs[log.channel] ?? (perChannelLogs[log.channel] = []);
  channelBuffer.push(normalizedLog);
  const bufferSize = channelDef?.bufferSize ?? 400;
  if (channelBuffer.length > bufferSize) {
    channelBuffer.splice(0, channelBuffer.length - bufferSize);
  }

  notifyListeners();
};

/**
 * Gets filtered logs by channel and optional timestamp range.
 */
export const getDiagnosticLogs = (
  filter?: { channel?: DiagnosticsChannelId; since?: number; tags?: string[] },
): DiagnosticLog[] => {
  let logs = diagnosticLogs;
  const { channel, tags } = filter ?? {};
  const since = filter?.since;

  if (channel) {
    logs = logs.filter((log) => log.channel === channel);
  }
  if (typeof since === 'number') {
    logs = logs.filter((log) => log.timestamp >= since);
  }
  if (tags && tags.length > 0) {
    logs = logs.filter(
      (log) => log.tags?.some((tag) => tags.includes(tag)) ?? false,
    );
  }
  return [...logs];
};

/**
 * Exports all logs as JSON string.
 */
export const exportDiagnosticLogs = (): string => {
  return JSON.stringify(
    {
      exportedAt: new Date().toISOString(),
      channelRegistry: registeredChannels,
      logs: diagnosticLogs,
    },
    null,
    2,
  );
};

/**
 * Clears all diagnostic logs.
 */
export const clearDiagnosticLogs = (): void => {
  diagnosticLogs.length = 0;
  Object.values(perChannelLogs).forEach((buffer) => {
    if (buffer) {
      buffer.length = 0;
    }
  });
  notifyListeners();
};

/**
 * Determines whether diagnostics should emit to the console.
 */
interface IdleVillageDiagnosticsEnv {
  VITE_IDLE_VILLAGE_DIAGNOSTICS?: string;
  VITE_ENABLE_SANDBOX_DIAGNOSTICS?: string;
}

export const isSandboxDiagnosticsRuntimeEnabled = (): boolean => {
  if (typeof window !== 'undefined') {
    if (window.__ENABLE_IDLE_VILLAGE_TEST_HOOKS) {
      return true;
    }
    if (window.__ENABLE_IDLE_VILLAGE_DIAGNOSTICS) {
      return true;
    }
  }

  if (typeof import.meta !== 'undefined') {
    const env = (import.meta.env ?? {}) as IdleVillageDiagnosticsEnv;
    if (env.VITE_IDLE_VILLAGE_DIAGNOSTICS === 'true' || env.VITE_ENABLE_SANDBOX_DIAGNOSTICS === 'true') {
      return true;
    }
  }

  return false;
};

const isDiagnosticsEnabled = (): boolean => isSandboxDiagnosticsRuntimeEnabled();

/**
 * Emits a diagnostics message when the current environment enables it.
 */
const emit = (
  level: 'log' | 'info' | 'warn' | 'debug',
  scope: string,
  message: string,
  payload?: unknown,
) => {
  if (!isDiagnosticsEnabled()) {
    return;
  }

  const prefix = `[IdleVillageSandbox:${scope}] ${message}`;
  if (payload !== undefined) {
    console[level](prefix, payload);
  } else {
    console[level](prefix);
  }
};

/**
 * Logging helpers that only emit when diagnostics are enabled.
 */
export interface SandboxDiagnostics<TPayload = unknown> {
  /** Emits a log-level message. */
  log: (message: string, payload?: TPayload, tags?: string[]) => void;
  /** Emits an info-level message. */
  info: (message: string, payload?: TPayload, tags?: string[]) => void;
  /** Emits a warn-level message. */
  warn: (message: string, payload?: TPayload, tags?: string[]) => void;
  /** Emits a debug-level message. */
  debug: (message: string, payload?: TPayload, tags?: string[]) => void;
  /** Emits an error-level message. */
  error: (message: string, payload?: TPayload, tags?: string[]) => void;
  /** Returns true when diagnostics will emit output. */
  isEnabled: () => boolean;
}

/**
 * Factory that scopes sandbox diagnostics to a specific module and channel.
 */
export function createSandboxDiagnostics<TPayload = unknown>(
  scope: string,
  channel: DiagnosticsChannelId = 'picker',
): SandboxDiagnostics<TPayload> {
  const buildLogger =
    (level: DiagnosticLog['level']) =>
    (message: string, payload?: TPayload, tags?: string[]) => {
      const consoleLevel = level === 'error' ? 'warn' : (level as 'log' | 'info' | 'warn' | 'debug');
      emit(consoleLevel, scope, message, payload);
      recordLog({
        channel,
        timestamp: Date.now(),
        level,
        scope,
        message,
        payload,
        tags,
      });
    };

  return {
    log: buildLogger('log'),
    info: buildLogger('info'),
    warn: buildLogger('warn'),
    debug: buildLogger('debug'),
    error: buildLogger('error'),
    isEnabled: () => isDiagnosticsEnabled(),
  };
}

export const createSandboxDiagnosticsChannel = createSandboxDiagnostics;
