export const STAT_DESCRIPTIONS = {
    // Core Stats
    hp: "Health Points. Represents the amount of damage a character can take before being defeated.",
    damage: "Base Damage. The raw damage dealt by attacks before multipliers or mitigation.",
    txc: "To Hit Chance (TxC). Improves accuracy. Countered by Evasion.",
    evasion: "Evasion. Reduces the chance of being hit. Counters TxC.",

    // Derived Stats
    htk: "Hits To Kill. The number of average hits required to defeat this character (HP / Damage).",
    hitChance: "Hit Chance %. The probability of landing a successful attack.",
    attacksPerKo: "Attacks Per KO. The average number of attacks needed to win, factoring in miss chance.",
    effectiveDamage: "Effective Damage. Average damage dealt per hit after accounting for enemy mitigation.",

    // Critical
    critChance: "Critical Chance %. Probability of landing a critical hit for increased damage.",
    critMult: "Critical Multiplier. Damage multiplier applied on critical hits (e.g., 2.0x).",
    critTxCBonus: "Critical Accuracy Bonus. Bonus to Hit Chance when a Critical Hit is rolled.",

    // Mitigation
    armor: "Armor. Flat damage reduction applied to incoming physical damage.",
    resistance: "Resistance %. Percentage reduction of incoming damage.",
    armorPen: "Armor Penetration. Ignores a flat amount of enemy Armor.",
    penPercent: "Penetration %. Ignores a percentage of enemy Resistance.",

    // Spell Stats
    cooldown: "Cooldown. Turns required to recharge the spell. Higher cooldowns allow for more powerful effects.",
    manaCost: "Mana Cost. Resource required to cast the spell.",
    scale: "Scaling. How much the spell benefits from the caster's stats.",
    duration: "Duration. How many turns the effect lasts.",
    aoe: "Area of Effect. Number of additional targets hit.",
    dangerous: "Danger Level. Threat generated by the spell.",
    eco: "Economy/Duration: Number of turns a DoT/HoT lasts or multiplier for resource efficiency.",
    castTime: "Cast Time: Time in seconds to cast the spell. Higher values leave you vulnerable but allow for stronger effects.",
    lifesteal: "Life Steal: Percentage of damage dealt returned as Health.",
    regen: "Health Regen: Amount of Health recovered per second/turn.",
    ward: "Ward: A temporary shield that absorbs damage before Health. Decays over time.",
    block: "Block Chance: Percentage chance to completely negate an attack's damage.",
    energyShield: "Energy Shield: A protective barrier that regenerates quickly when not taking damage."
};
