/**
 * Canonical Store Verification Test Suite
 * 
 * CR-005: Verify Both Surfaces Consume Same Canonical Source
 * 
 * This test suite verifies that both /test and /minimal-gameplay surfaces consume
 * the same canonical Village Resident Store with identical data and behavior.
 * 
 * Verification scope:
 * - Data consistency: residents data identical on both pages
 * - Behavior consistency: drag & drop, validation, state management identical
 * - Store instance sharing: both pages read from same store instance
 * - Telemetry consistency: telemetry events generated by both pages match
 * - Error handling: fallback scenarios tested on both pages
 * 
 * Runtime behavior is NOT modified - this is verification only.
 */

import { render, screen, waitFor } from '@testing-library/react';
import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import type { ResidentState } from '@/engine/game/idleVillage/TimeEngine';
import { storeConsistencyChecker, type VerificationReport } from '@/ui/idleVillage/verification/StoreConsistencyChecker';
import { useVillageResidentStore } from '@/ui/idleVillage/store/VillageResidentStore';
import { useVillageResidents } from '@/ui/idleVillage/hooks/useVillageResidents';

/**
 * Mock resident data for testing
 */
const mockResidents: ResidentState[] = [
  {
    id: 'resident-1',
    displayName: 'Test Resident 1',
    status: 'available',
    fatigue: 0,
    currentHp: 100,
    maxHp: 100,
    isHero: false,
    isInjured: false,
    statSnapshot: { hp: 100, strength: 50, agility: 50 },
    statTags: [],
    portraitUrl: undefined,
    survivalCount: 0,
    survivalScore: 0,
  },
  {
    id: 'resident-2',
    displayName: 'Test Resident 2',
    status: 'available',
    fatigue: 10,
    currentHp: 80,
    maxHp: 100,
    isHero: true,
    isInjured: false,
    statSnapshot: { hp: 80, strength: 70, agility: 60 },
    statTags: [],
    portraitUrl: undefined,
    survivalCount: 5,
    survivalScore: 100,
  },
];

/**
 * Test hook to access store state directly
 */
function useTestStoreState() {
  return useVillageResidentStore(state => ({
    residents: state.residents,
    isLoading: state.isLoading,
    error: state.error,
    usedFallback: state.usedFallback,
  }));
}

describe('CR-005: Canonical Store Verification', () => {
  beforeEach(() => {
    // Clear store state before each test
    const store = useVillageResidentStore.getState();
    store.clearResidents();
    storeConsistencyChecker.clearResults();
  });

  afterEach(() => {
    // Clean up after each test
    const store = useVillageResidentStore.getState();
    store.clearResidents();
  });

  describe('Store Instance Verification', () => {
    it('should verify both surfaces use the same store instance', () => {
      const result = storeConsistencyChecker.verifyStoreInstance();
      
      expect(result.isSameInstance).toBe(true);
      expect(result.verificationMethod).toBe('reference-identity-check');
      expect(result.testSurfaceStoreId).toBe(result.minimalSurfaceStoreId);
    });

    it('should log store instance verification results', () => {
      storeConsistencyChecker.verifyStoreInstance();
      const results = storeConsistencyChecker.getCheckResults();
      
      expect(results).toHaveLength(1);
      expect(results[0].checkName).toBe('Store Instance Verification');
      expect(results[0].isConsistent).toBe(true);
    });
  });

  describe('Data Consistency Verification', () => {
    it('should verify identical resident data between surfaces', async () => {
      // Compare data (both surfaces read from same store, so should be identical)
      const result = storeConsistencyChecker.compareResidentData(
        mockResidents,
        mockResidents
      );

      expect(result.isIdentical).toBe(true);
      expect(result.testSurfaceCount).toBe(mockResidents.length);
      expect(result.minimalSurfaceCount).toBe(mockResidents.length);
      expect(result.missingInMinimal).toHaveLength(0);
      expect(result.missingInTest).toHaveLength(0);
      expect(result.dataDifferences).toHaveLength(0);
    });

    it('should detect missing residents in minimal surface', () => {
      const testResidents = mockResidents;
      const minimalResidents = [mockResidents[0]]; // Missing second resident

      const result = storeConsistencyChecker.compareResidentData(
        testResidents,
        minimalResidents
      );

      expect(result.isIdentical).toBe(false);
      expect(result.missingInMinimal).toContain('resident-2');
      expect(result.testSurfaceCount).toBe(2);
      expect(result.minimalSurfaceCount).toBe(1);
    });

    it('should detect missing residents in test surface', () => {
      const testResidents = [mockResidents[0]]; // Missing second resident
      const minimalResidents = mockResidents;

      const result = storeConsistencyChecker.compareResidentData(
        testResidents,
        minimalResidents
      );

      expect(result.isIdentical).toBe(false);
      expect(result.missingInTest).toContain('resident-2');
      expect(result.testSurfaceCount).toBe(1);
      expect(result.minimalSurfaceCount).toBe(2);
    });

    it('should detect data differences between residents', () => {
      const testResidents = JSON.parse(JSON.stringify(mockResidents)) as ResidentState[];
      const minimalResidents = JSON.parse(JSON.stringify(mockResidents)) as ResidentState[];
      
      // Modify fatigue in minimal surface
      minimalResidents[0].fatigue = 50;

      const result = storeConsistencyChecker.compareResidentData(
        testResidents,
        minimalResidents
      );

      expect(result.isIdentical).toBe(false);
      expect(result.dataDifferences).toContain('resident-1');
      
      const comparison = result.propertyComparisons.get('resident-1');
      expect(comparison?.isEqual).toBe(false);
      expect(comparison?.propertyName).toBe('fatigue');
    });

    it('should log data consistency verification results', () => {
      storeConsistencyChecker.compareResidentData(mockResidents, mockResidents);
      const results = storeConsistencyChecker.getCheckResults();
      
      expect(results).toHaveLength(1);
      expect(results[0].checkName).toBe('Data Consistency');
      expect(results[0].isConsistent).toBe(true);
    });
  });

  describe('Behavior Consistency Verification', () => {
    it('should verify drag & drop behavior consistency', () => {
      const result = storeConsistencyChecker.verifyBehaviorConsistency();
      
      expect(result.dragDropConsistent).toBe(true);
      expect(result.findings.dragDrop).toContain(
        'Both surfaces use useResidentDropValidation hook'
      );
    });

    it('should verify validation logic consistency', () => {
      const result = storeConsistencyChecker.verifyBehaviorConsistency();
      
      expect(result.validationConsistent).toBe(true);
      expect(result.findings.validation).toContain(
        'Both surfaces use residentDropRules for validation'
      );
    });

    it('should verify state management consistency', () => {
      const result = storeConsistencyChecker.verifyBehaviorConsistency();
      
      expect(result.stateManagementConsistent).toBe(true);
      expect(result.findings.stateManagement).toContain(
        'Both surfaces use Village Resident Store for resident state'
      );
    });

    it('should log behavior consistency verification results', () => {
      storeConsistencyChecker.verifyBehaviorConsistency();
      const results = storeConsistencyChecker.getCheckResults();
      
      expect(results).toHaveLength(1);
      expect(results[0].checkName).toBe('Behavior Consistency');
      expect(results[0].isConsistent).toBe(true);
    });
  });

  describe('Telemetry Consistency Verification', () => {
    it('should verify telemetry events are consistent', () => {
      const result = storeConsistencyChecker.verifyTelemetryConsistency();
      
      expect(result.isConsistent).toBe(true);
      expect(result.testSurfaceEvents.length).toBeGreaterThan(0);
      expect(result.minimalSurfaceEvents.length).toBeGreaterThan(0);
      expect(result.missingInMinimal).toHaveLength(0);
      expect(result.missingInTest).toHaveLength(0);
    });

    it('should include expected telemetry events', () => {
      const result = storeConsistencyChecker.verifyTelemetryConsistency();
      
      const expectedEvents = [
        'village_resident_store_bootstrap_success',
        'village_resident_store_bootstrap_error',
        'resident_assign',
        'resident_unassign',
      ];

      for (const event of expectedEvents) {
        expect(result.testSurfaceEvents).toContain(event);
        expect(result.minimalSurfaceEvents).toContain(event);
      }
    });

    it('should log telemetry consistency verification results', () => {
      storeConsistencyChecker.verifyTelemetryConsistency();
      const results = storeConsistencyChecker.getCheckResults();
      
      expect(results).toHaveLength(1);
      expect(results[0].checkName).toBe('Telemetry Consistency');
      expect(results[0].isConsistent).toBe(true);
    });
  });

  describe('Error Handling Verification', () => {
    it('should verify error handling consistency', () => {
      const result = storeConsistencyChecker.verifyErrorHandling();
      
      expect(result.isConsistent).toBe(true);
      expect(result.testedScenarios.length).toBeGreaterThan(0);
    });

    it('should test common error scenarios', () => {
      const result = storeConsistencyChecker.verifyErrorHandling();
      
      const expectedScenarios = [
        'Empty character storage',
        'Character conversion failure',
        'Store initialization failure',
        'Persistence failure',
      ];

      for (const scenario of expectedScenarios) {
        expect(result.testedScenarios).toContain(scenario);
      }
    });

    it('should verify both surfaces handle errors consistently', () => {
      const result = storeConsistencyChecker.verifyErrorHandling();
      
      for (const [scenario, scenarioResult] of result.scenarioResults) {
        expect(scenarioResult.testSurfaceHandled).toBe(true);
        expect(scenarioResult.minimalSurfaceHandled).toBe(true);
        expect(scenarioResult.errorMessagesConsistent).toBe(true);
      }
    });

    it('should log error handling verification results', () => {
      storeConsistencyChecker.verifyErrorHandling();
      const results = storeConsistencyChecker.getCheckResults();
      
      expect(results).toHaveLength(1);
      expect(results[0].checkName).toBe('Error Handling');
      expect(results[0].isConsistent).toBe(true);
    });
  });

  describe('Complete Verification Report', () => {
    it('should generate complete verification report', () => {
      const report = storeConsistencyChecker.generateReport(
        mockResidents,
        mockResidents
      );

      expect(report).toHaveProperty('storeInstance');
      expect(report).toHaveProperty('dataConsistency');
      expect(report).toHaveProperty('behaviorConsistency');
      expect(report).toHaveProperty('telemetryConsistency');
      expect(report).toHaveProperty('errorHandling');
      expect(report).toHaveProperty('overallStatus');
      expect(report).toHaveProperty('summary');
      expect(report).toHaveProperty('timestamp');
    });

    it('should report pass status when all checks pass', () => {
      const report = storeConsistencyChecker.generateReport(
        mockResidents,
        mockResidents
      );

      expect(report.overallStatus).toBe('pass');
    });

    it('should report partial status when some checks fail', () => {
      // Create different data to trigger failure
      const differentResidents = [{ ...mockResidents[0], fatigue: 999 }];

      const report = storeConsistencyChecker.generateReport(
        mockResidents,
        differentResidents
      );

      expect(report.overallStatus).toBe('partial');
    });

    it('should include summary of all check results', () => {
      const report = storeConsistencyChecker.generateReport(
        mockResidents,
        mockResidents
      );

      expect(report.summary.length).toBeGreaterThan(0);
      expect(report.summary).toContainEqual(
        expect.stringContaining('Store Instance Verification: PASS')
      );
      expect(report.summary).toContainEqual(
        expect.stringContaining('Data Consistency: PASS')
      );
    });
  });

  describe('Integration with useVillageResidents Hook', () => {
    it('should verify hook accesses canonical store', () => {
      const TestComponent = () => {
        const { residents } = useVillageResidents();
        return <div data-testid="resident-count">{residents.length}</div>;
      };

      render(<TestComponent />);

      const countElement = screen.getByTestId('resident-count');
      // Hook accesses canonical store, count may vary based on store state
      expect(countElement).toBeInTheDocument();
    });
  });

  describe('Results Management', () => {
    it('should clear all check results', () => {
      storeConsistencyChecker.verifyStoreInstance();
      storeConsistencyChecker.verifyBehaviorConsistency();
      
      expect(storeConsistencyChecker.getCheckResults()).toHaveLength(2);
      
      storeConsistencyChecker.clearResults();
      
      expect(storeConsistencyChecker.getCheckResults()).toHaveLength(0);
    });

    it('should accumulate check results across multiple calls', () => {
      storeConsistencyChecker.verifyStoreInstance();
      storeConsistencyChecker.verifyBehaviorConsistency();
      storeConsistencyChecker.verifyTelemetryConsistency();
      
      const results = storeConsistencyChecker.getCheckResults();
      
      expect(results).toHaveLength(3);
      expect(results[0].checkName).toBe('Store Instance Verification');
      expect(results[1].checkName).toBe('Behavior Consistency');
      expect(results[2].checkName).toBe('Telemetry Consistency');
    });
  });
});
